### ISSUE TITLE
Show artist name on lock screen

### ISSUE THREAD

**Issue by quite** [vanilla-music/vanilla#132] opened 2015-01-22 11:28 UTC
On my device, artist name is not shown on the lock screen. Album and song are.

Possibly this is specific to my device, nexus 5, or  screen size. If so, I would sacrifice the vanilla icon for the artist name.

Even if I "pull down" the vanilla app field on the lock screen, nothing more is shown.

**Comment by aminb** [comment] 2015-01-22 20:45
I'm assuming you're on Lollipop?

I'm on Lollipop and I don't have this issue. I see the song name and artist, and when I expand the notification, I see the song name, artist and album.

Can you provide a screenshot?

**Comment by quite** [comment] 2015-01-22 21:40
Ah, no. I'm on 4.4.4, well, Cyanogenmod 11 M11.
![screenshot_2015-01-22-22-38-12](https://cloud.githubusercontent.com/assets/488679/5865134/8f41e9ee-a287-11e4-9595-15b1e92f02e6.png)

**Comment by aminb** [comment] 2015-01-23 17:55
@adrian-bl Can you look into this Adrian?

**Comment by adrian-bl** [comment] 2015-01-25 08:19
AFAIK there is nothing we can do about: Vanilla Music doesn't 'create' the lockscreen: It just sends android information about the cover, album, title and artist - it is then at androids discretion to display whatever information it wants to display.

How does your lockscreen look like on some other player? (eg: apollo)

**Comment by quite** [comment] 2015-01-25 12:56
Aha, that's how it works. So, now it gets interesting.

With Apollo I get this on the lockscreen:

app icon
song title
artist - album

but with Vanilla only:

app icon
song title
artist

**Comment by adrian-bl** [comment] 2015-02-01 16:55
@aminb what do you think: should we just change 'album' to 'artist - album' (this would affect the lockscreen and bluetooth devices)

**Comment by aminb** [comment] 2015-02-01 18:10
@adrian-bl I think that would make sense and it's nice to have the artist name as well.

In that case, we should do simple checks if any of 'artist' or 'album' are empty and change the output format accordingly. For instance, to avoid these:
`- album`  (empty artist name)
`artist -`  (empty album name)

**Comment by adrian-bl** [comment] 2015-02-15 17:35
Should be fixed with https://github.com/vanilla-music/vanilla/commit/c28564ae8d0c8024bdead40e96947ef829dda463

**Comment by breversa** [comment] 2015-10-26 17:49
Sadly, the artist name is no longer displayed in v1.0.33 (on CyanogenMod 11 - Android 4.4.4). Instead, there is Vanilla speaker icon.

Track name and album are displayed fine underneath.

**Comment by aminb** [comment] 2015-10-27 01:04
Confirmed, re-opening.

**Comment by aminb** [comment] 2015-10-27 01:07
I believe this is the cause: https://github.com/vanilla-music/vanilla/commit/e4855e51ebd146e5b77550175f33064ee1e32d43

**Comment by adrian-bl** [comment] 2015-10-27 08:36
Yes, this is caused by https://github.com/vanilla-music/vanilla/commit/e4855e51ebd146e5b77550175f33064ee1e32d43 which fixes tags on bluetooth devices.

Unfortunately, we can not set different information for the lockscreen + bt devices, so we have to choose between one of these 3 behaviours:

1. https://github.com/vanilla-music/vanilla/commit/c28564ae8d0c8024bdead40e96947ef829dda463 : Set title=title, album=artist+album, artist=null (1.0.32)

2. https://github.com/vanilla-music/vanilla/commit/e4855e51ebd146e5b77550175f33064ee1e32d43 : Set title=title, album=album, artits=artist (1.0.33)

3. ..or some other crazy hack: title=title, album=artist+album artist=artist

I clearly prefer the current behaviour (2) as it is the 'correct' way to do it.

**Comment by aminb** [comment] 2015-10-29 02:10
Well, from a theoretical point of view I'd prefer (2) as it is, as you said, the *correct* behaviour. However, I think it's nice to be able to see the artist on lock screen as well (although this is something Android as a whole should be taking care of but is not).

Let's see what everyone else thinks. We can go by majority.

**Comment by breversa** [comment] 2015-10-29 08:27
Well, I too would prefer to do the things "right", hence (2), especially if
there's a foreseeable way for Android to take care of it in the future (WMG
: maybe an Xposed module ?).

However, as Amin said, functionnality may prime over code, so any solution
that allows to see the artist+title+album on both the lockscreen and BT
devices is fine to me, provided it's precisely commented in the code for
future reference (or maybe even an optionnal compilation flag ?).

2015-10-29 3:10 GMT+01:00 Amin Bandali <notifications@github.com>:

**Comment by adrian-bl** [comment] 2015-10-29 09:33
> Well, I too would prefer to do the things "right", hence (2), especially if there's a foreseeable way for 
> Android to take care of it in the future (WMG : maybe an Xposed module ?).

The 'native' lockscreen controlls are dead anyway on Android 5.0: Lollipop and later only displays the notification on the lockscreen. (Unfortunately, only the small version is displayed :-( )

So how about this: We go with #2 for anything >= 5.0 and use #3 for devices with native lockscreen controlls (aka 4.x) ?

We will end up with some special code for 4.x anyways after we migrated to the new RemoteControll class of 5.x and later - so having a different behavior on 4.x devices doesn't hurt much.

**Comment by breversa** [comment] 2015-10-29 09:35
Fine by me. :-)

I'm not the coder anyway. ;-)

2015-10-29 10:33 GMT+01:00 Adrian Ulrich <notifications@github.com>:

**Comment by aminb** [comment] 2015-10-29 16:01
Sounds like a good compromise, so :+1: from me too!

**Comment by adrian-bl** [comment] 2015-12-23 16:41
We are now using two seperated lockscreen implementations.

Commit https://github.com/vanilla-music/vanilla/commit/f8ce79b9ce5b8a81a2f7e91cf5ae237840ea55ec restores the 'old' metadata-style on ICS devices while the 5.x code uses the correct way to publish metadata.

**Closed by adrian-bl** 2015-12-23 16:41 UTC
Labels: bug
