### ISSUE TITLE
Seekbar does not display when no cover art

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#1082] opened 2021-04-03 21:35 UTC
- Vanilla Music Version (Settings -> About): 1.0.91
- Android Version: 10 (LOS 17.1)
- Phone vendor / model: Xiaomi Mi 5
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

The seekbar is only visible when the track playing has a cover art and the notification is in expanded state. When there is none, the notification shrinks and becomes compact, leaving only the 3 action buttons, and no arrow button to expand it, either.

For reference, Poweramp shows an expanded notification even if there is no cover art.

**Comment by adrian-bl** [comment] 2021-04-04 06:30
Hmm, this works for me on LOS 18.1

![Screenshot_20210404-082438_Vanilla_Nightly](https://user-images.githubusercontent.com/568734/113500626-cbc2d400-951f-11eb-9581-78a139affe8e.png)


Are you sure that you cant expand the notification by dragging it?

1.0.91 uses the appcompat notification, so it would be very strange if this was only broken on Android 10 but not 11

**Comment by opusforlife2** [comment] 2021-04-04 18:40
@adrian-bl Yeah, I just tried it again. There is no expansion arrow to tap, and expanding by trying to drag downwards doesn't work either.

**Comment by adrian-bl** [comment] 2021-04-06 06:40
Interesting: i can reproduce this on LOS17 too - that's just silly :-/

Well.. i guess we can just give Android a fake / placeholder cover

**Comment by opusforlife2** [comment] 2021-04-06 19:46
Thanks!

**Comment by adrian-bl** [comment] 2021-04-11 07:20
This should be fixed with 4c290f0e3fc30f58a0159535bf59979c0fc02333

**Closed by adrian-bl** 2021-04-11 07:20 UTC

**Comment by opusforlife2** [comment] 2021-04-17 06:27
@adrian-bl Thanks! The notification now stays expanded, making the seekbar available. However, it is bright white in colour, even when system theme is set to dark, making it contrast jarringly with other dark themed notifications.

Do you want me to open a new issue for this?

**Comment by adrian-bl** [comment] 2021-04-18 13:29
> However, it is bright white in colour, even when system theme is set to dark

I don't think that the notification itself should follow the app theme - it should follow the system theme, which it does on Android 11.

But i've submitted cf9aa1df0ea42451e6720545aa2dc6a5c7f23399 which changes the notification to use the same icon as the widgets do (+ the library view) - which happens to be dark.

**Comment by opusforlife2** [comment] 2021-04-18 20:33
Ah. Thanks. Hopefully that works.

Confusingly, both my app theme and system theme happened to be dark, but I still got a white notification for some reason.

**Comment by opusforlife2** [comment] 2021-05-02 20:18
@adrian-bl Could you release a new version with this fix soon? Seeing the contrast all the time is pretty discomforting.

**Comment by opusforlife2** [comment] 2021-09-04 07:46
@adrian-bl Hi. Sorry to ask this again, but I've been using the bright white notification for many months now. Could you please release the new version since it's already fixed in the code?

**Comment by opusforlife2** [comment] 2022-01-25 18:24
@adrian-bl Ping.

**Comment by opusforlife2** [comment] 2022-07-21 17:52
@adrian-bl Biannual ping.
