### ISSUE TITLE
Feature request: choice of observed folder(s)

### ISSUE THREAD

**Issue by muellerfranz** [vanilla-music/vanilla#500] opened 2017-01-08 18:00 UTC
First of all: thanks a lot for this great music player and all the voluntary work that the developer(s) put into building it! A lot of people owe you a beer (or any other drink of your choice).

My request is (hopefully) relatively simple.
I would very much like to be able to choose which folders are "scanned/taken into consideration".
So one could choose that only the content of one or more music folders is read into the tag-based library. That way podcasts and audio-books don't overcrowd the music-library and the shuffle function.

Maybe this feature does not even need to be implemented in the GUI - although I and maybe also others would very much like that - and can be achieved via changes in some config-file.
So, if someone knows which changes in what file that would be, that would obviously also be very helpful and welcome.

**Comment by adrian-bl** [comment] 2017-01-08 18:24
This is an old feature request (See #22) which will hopefully soon be implemented as we are now using our own media library (instead of androids own implementation).

Closing this issue as a duplicate of #22

**Closed by adrian-bl** 2017-01-08 18:24 UTC
