### ISSUE TITLE
No songs on previously created playlists

### ISSUE THREAD

**Issue by bobolea** [vanilla-music/vanilla#642] opened 2017-07-25 15:42 UTC
- Vanilla Music Version (Settings -> About):
- Android Version: 1.0.53
- Phone vendor / model: Nokia 6
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x ] NA / Don't know.

## Description
The playlists that were created on my previous Blackberry 10 phone do not show any tracks on them, these show correctly on Google music.
....

## Steps to reproduce the issue
Open playlists
...

## Screenshot / Video (If applicable)

...

**Comment by bobolea** [comment] 2017-07-26 19:08
Thats great, it worked perfectly. Thanks for the quick response.

**Comment by andiandi13** [comment] 2017-07-26 19:16
You're welcome.

**Comment by andiandi13** [comment] 2017-07-26 19:20
@bobolea You can close the issue :)

**Comment by adrian-bl** [comment] 2017-07-26 19:23
Closing this, also kind of a duplicate of #643

**Closed by adrian-bl** 2017-07-26 19:23 UTC
