### ISSUE TITLE
Configurable music folder

### ISSUE THREAD

**Issue by mase76** [vanilla-music/vanilla#165] opened 2015-04-20 14:03 UTC
Hi!
Vanilla adds all the ringtones and other soundfiles from apps to its
library. For the appfiles I can use the .nomedia file, but not for ringtones,
alarms, etc. I would suggest to let the use configure one or more music
folders.

**Comment by adrian-bl** [comment] 2015-04-20 17:32
duplicate of bug 22

**Closed by adrian-bl** 2015-04-20 17:32 UTC
