### ISSUE TITLE
Enqueue if playing; Play if paused broken

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#148] opened 2015-03-22 16:37 UTC
In the new version 0.9.42, songs are added to the queue even if the now playing song is paused (instead of being played in a new queue).

**Comment by adrian-bl** [comment] 2015-03-23 18:41
Could you give us some more details about the expected behaviour and what exactly you are doing?

I just tested this:
-> Pause song and go to library view
-> Hit 'enqueue song' -> song is added to queue but still paused
-> Hit 'play as next' -> song is added to the queue but still paused
-> Hit 'play' -> queue is flushed and song is playing.

Did you expect a different outcome?

**Comment by ToNIX-** [comment] 2015-03-23 21:10
In the library view (artists tab), with the queue paused, pressing on an artist adds all the songs to the queue instead of clearing the queue and playing it's songs. 

The same behavior happens in the album or songs tab. In 0.9.41, the behavior was the same as long press + play.

**Comment by pinnie** [comment] 2015-03-24 08:41
I'm also experiencing this behaviour with "Enqueue if playing; Play if paused" (in my case, after updating from 0.9.40 to 0.9.42).

**Comment by aminb** [comment] 2015-03-24 12:20
@adrian-bl Basically, the `onItemClicked` behaviour for the listviews has changed, due to 7d21710. I've noticed this too.

Right now, whenever you tap on a song, it's always "enqueued as next".

**Comment by adrian-bl** [comment] 2015-03-24 12:52
I also suspect commit 7d21710, reverting it would probably fix the issue (i'll give it a try today or tomorrow) - but i wonder how the code actually worked:  ACTION_PLAY_OR_ENQUEUE is never sent in an async message - that's why i removed the code.

**Comment by adrian-bl** [comment] 2015-03-24 21:40
The issue should be fixed with 7fabf739d6b34bb77ff5d52cd28cc472440f7d21.
@aminb Could you have a look at it and close the issue if it works for you?

**Comment by aminb** [comment] 2015-03-25 00:35
@adrian-bl The issue is indeed fixed with 7fabf73 for me.

**Closed by aminb** 2015-03-25 00:35 UTC
Labels: bug
