### ISSUE TITLE
If no cover art embedded in music file, lockscreen displays the last cover available

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#146] opened 2015-03-16 08:52 UTC
I noticed the following behaviour :
- If a music fil has no embedded cover, the lockscreen displays the default background picture :
![screenshot_2015-03-16-09-56-51 1](https://cloud.githubusercontent.com/assets/2071276/6663072/32ae06a8-cbc3-11e4-8e7a-5b89eb92babc.png)

- If a music file has an embedded cover, it's displayed on the lockscreen. So far, so good (and both Aquaria game AND soundtrack are real gems, by the way. :-P ) :
![screenshot_2015-03-16-09-39-22](https://cloud.githubusercontent.com/assets/2071276/6662965/e6690654-cbc1-11e4-8b5c-dc6e51878192.png)

- However, if the next (and subsequent) files do not have embedded art, the lockscreen still displays the last cover available :
![screenshot_2015-03-16-09-39-40](https://cloud.githubusercontent.com/assets/2071276/6662977/0bd64c12-cbc2-11e4-9842-7333c8bcd653.png)

- When a subsequent file has an embedded cover, it will again be displayed normally.

Expected behaviour :
- If no cover embedded in music file, the lockscreen should display the default lockscreen background picture.

(I took the first screenshot last as an afterthought to add clarity, hence the time)

Device : Samsung Galaxy Nexus (maguro)
ROM : CyanogenMod 11 M12

**Comment by Allanitomwesh** [comment] 2015-04-16 14:58
I can confirm this bug. Had it recently when I played a track I received over Bluetooth with no art. The lock screen shows the previous track's art.

**Comment by adrian-bl** [comment] 2015-04-25 15:17
This seems to be an android bug: I've seen this some times on 4.x and i have the impression that it was fixed in 5.0:

VanillaMusic passes a value of 'false' to Android if the song has no cover, see:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/RemoteControl.java#L100

It seems, that this (sometimes?) causes android to simply display the old cover.
The only way we could work around this issue would be to pass a default cover to the RemoteControl class in such a case.

**Comment by un-logic** [comment] 2015-04-27 04:03
I was experiencing same behavior when running on KitKat, but update to Lollipop did solved the problem. 
As for workaround, some might find default cover art not so attractive. I don't know if RemoteControl class supports alpha channel of say PNG, because if it does, then we could pass an almost fully transparent blank cover art image to imitate screen update. And again this bug is clearly related to Android.

**Comment by adrian-bl** [comment] 2015-04-27 07:21
The transparent PNG is a nice idea - i'll give it a try.

**Comment by adrian-bl** [comment] 2015-05-01 20:13
Unfortunately, using a transparent PNG does not work: Android (at least 4.2) displays the transparent area as black - so this is not an option.

I'm closing this bug as there is nothing we can do as this is an Android bug - and it seems to be fixed in 5.x

**Closed by adrian-bl** 2015-05-01 20:13 UTC
Labels: bug

**Comment by un-logic** [comment] 2015-08-15 19:45
I'll just add a few pennies.
As previously mentioned, update to Lollipop did solved this bug related to RemoteControl class, but infamous Samsung engeenears was able to reproduce such an ill behaviour for S-View cover layout even running on Lollipop! Just like on Kitkat it preserves latest available Album Art if currently playing song lacks one.
I think there is another workaround that can fix both Kitkat's RemoteControl class and Samsung's S-view cover layout. I suggest to forcefully replace current Album Art with default cover at every track change (manual or automatic) right after file or stream close or release or termination (not sure about terminology and mechanics being used) and then pass control to an existing Album Art broadcasting algorithm, which will replace cover once again, if it present, of course, as soon as new track will start to play. This might not only fix KitKat and S-view, but also preserve current behaviour for Lollipop's RemoteControl class.
So, what do you think about it?
Sorry for lots of words by the way.

**Comment by adrian-bl** [comment] 2015-08-19 17:47
I created a different work around for this:
https://github.com/vanilla-music/vanilla/commit/de4b15f4ab1d5b6ac818eece05a5b69625216037

Vanilla Music will now send a 100% transparent image as a fallback cover, forcing the code to update the lock screen (while showing the wallpaper - or a black screen in the worst case (?)).

**Comment by KonomiKitten** [comment] 2015-09-29 01:50
Has this hit the Google Play store? I am having this problem but with a twist. Even after I exit Vanilla Music the lock screen still has the cover art, even though I closed the program. I have to set my wallpaper all over again, very annoying.

**Comment by adrian-bl** [comment] 2015-09-29 05:47
Yes, its in 1.0.31

What kind of Phone & OS Version are you using?

**Comment by KonomiKitten** [comment] 2015-09-29 06:21
I'm using Vanilla Music 1.0.31, Android 5.0.2 and the phone is a Motorola Moto E 2nd Gen.

**Comment by adrian-bl** [comment] 2015-09-29 12:02
@KonomiKitten How reliable are you to reproduce this issue? Does it happen always or just sometimes?
I've seen it like 3 times on my HTC One X (4.2) but never had it happen on Lollipop.

This is the code we are using to update the lockscreen:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/RemoteControl.java#L86 .. and we are doing almost exactly the same as the old 2.2 Music-App.

The only thing i could think of is to call clear(), (but setting new data is supposed to just overwrite the existing data)

@breversa Did 1.0.31 fix the issue for you?

**Comment by breversa** [comment] 2015-09-29 12:04
Yes, the issue is totally solved, at least on CyanogenMod 11/Android 4.4.4 :-)

**Comment by KonomiKitten** [comment] 2015-09-29 12:44
@adrian-bl It happens every single time album art is on the screen, 100% reproducible on my phone. I honestly wish I could just turn it off all together because some of the album art on my tracks is a bit risqué... Anyway basically when art is on there I stop the song exit Vanilla Music, check the lock screen the art is still there. It takes setting a different wallpaper then setting the wallpaper back to my old version to fix it.

**Comment by adrian-bl** [comment] 2015-10-01 15:42
@KonomiKitten Could you please give this version a try:
https://mega.nz/#!GsliEISJ!f12406E_AuM9WhGcixXSweXeT_25Gkd4fp6K75i23w4

(It is signed with my play-release key, so you should be able to upgrade)

This version calls clear() on the metadata editor before applying any changes.
Please let me know if it makes any difference.

An option to disable artwork on the lockscreen is planned. I'll probably get around to do it this month.

**Comment by KonomiKitten** [comment] 2015-10-01 15:57
@adrian-bl Unfortunately that made it worse somehow. I'm going to state the exact steps this time.

Getting cover art stuck: Run Vanilla Music -> Play a song -> Switch to Home Screen -> Pull down notifications -> Use the X on the Vanilla Music Notification -> Lock Phone -> Check Lock Screen album art stuck.

Only this time around I couldn't actually restore my lock screen by switching the wallpaper. I had to open Google Play Music, have it change the album art on the lock screen then close it. That got my lock screen back to my wallpaper.

I confirmed I had the new version installed and made sure to force stop after updating the app so it would be running. The version shown was 1.0.32 for Vanilla Music.

Harbinger of bad news...

**Comment by adrian-bl** [comment] 2015-10-01 17:17
Hmm.. i did this on two devices (Running CM12 and AOSP 4.2) and both devices do not have any issues.

..but then i digged out my old Moto G and it does in fact have this issue.
I'll check if i can find a workaround for this motorola-only (?) bug

**Comment by KonomiKitten** [comment] 2015-10-01 17:22
@adrian-bl It's possible, I only have one phone to test though glad you have so many to check. It's strange that it only affects Vanilla Music and not GoneMAD Music Player or Google Play Music.

**Comment by adrian-bl** [comment] 2015-10-01 20:57
> It's strange that it only affects Vanilla Music and not GoneMAD Music Player or Google Play Music.
I suppose that they are just lucky: This seems to be some strange motorola race condition:

We are calling stopForeground(), so the system is supposed to remove our clutter. This works fine on non-motorola devices, and even there it sometime does: On my phone, some *songs* are not affected while others are affected in about 90% of my tests. (And adding a simple Log.d() changes the chances of hitting the issue)

Anyway: Could you please give
https://mega.nz/#!H10XHApA!laU65u_sO4qo6MA5BD85qy1-jqGs7vxIsRUCdeldAVw
a shot?

This version (forcefully) clears the displayed bitmap if the notification will not stay visible.

**Comment by KonomiKitten** [comment] 2015-10-02 01:04
@adrian-bl First test shows this build fixes the problem, yay!

**Comment by adrian-bl** [comment] 2015-10-03 07:00
@KonomiKitten great: thanks for your feedback!
I pushed the change to the master (https://github.com/vanilla-music/vanilla/commit/d92f01d01f91d66eae79356dc8f19e9d6e446039), it will be included in the 1.0.32-playstore release (but not in the 1.0.32 f-droid as this build was already released 2 days ago)
