### ISSUE TITLE
sd scanner not working in 1.0.45

### ISSUE THREAD

**Issue by nixingizgood** [vanilla-music/vanilla#481] opened 2016-11-26 20:33 UTC
In 1.0.45 from F-Droid, I am not able to get an updated db via the included SD scanner. Reverted to 1.0.44 and the SD scanner works again.

**Comment by adrian-bl** [comment] 2016-11-27 11:06
Do you see anything in the log while starting the scanner?

There were some changes to the SD-Scanner in 1.0.45 - but we mostly improved the detection of storage paths - which seems to fail on your phone.

Also: What version of Android are you using?

**Comment by nixingizgood** [comment] 2016-11-27 16:09
I am using Android 5.0...

In 1.0.45, upon pressing "Start Rescan",  the bottom text immediately updates to "Completed, ready to start another scan". No intermediate text and the progress bar never updates. 

1.0.44... the scan takes a couple of seconds with various "Preparing", "Processed" or "Examined" text tidbits appearing plus the progress bar fills up.

**Comment by apikozh** [comment] 2016-11-27 23:49
I have same problem with 1.0.45 and 1.0.46 from F-droid. In 1.0.44 all works fine.

Additionally, I clone and built "medialibrary" branch from GitHub and it shows empty library.

Android 5.0.2
Firmware MIUI 8.0.1

**Comment by adrian-bl** [comment] 2016-11-28 10:42
> I am using Android 5.0...

@nixingizgood ok, that's odd: it works just fine for me on all my 5.x phones (CM12, Motorola, AOSP)
Whats your phone model / vendor ?
Are you able to browse /storage/emulated/0 in the files tab? (And: what is the starting point you see there?)

> Additionally, I clone and built "medialibrary" branch from GitHub and it shows empty library.

@apikozh that's bad, as the medialibrary branch uses similar code to detect the music directories.

Do you see any error message if you add
```
 Log.v("VanillaMusic", "Exception: "+e)
```

at 
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/SDScannerFragment.java#L171 (in the master branch - and don't forget to import android.util.Log') ?

**Comment by apikozh** [comment] 2016-11-28 12:15
@adrian-bl It seems that no error appears in log, when I press Start scan button, but at program startup "Failed to load state" exception throws:

`W/VanillaMusic: Failed to load state
                java.io.FileNotFoundException: /data/data/ch.blinkenlights.android.vanilla/files/state: open failed: ENOENT (No such file or directory)
                    at libcore.io.IoBridge.open(IoBridge.java:496)
                    at java.io.FileInputStream.<init>(FileInputStream.java:76)
                    at android.app.ContextImpl.openFileInput(ContextImpl.java:1086)
                    at android.content.ContextWrapper.openFileInput(ContextWrapper.java:185)
                    at ch.blinkenlights.android.vanilla.PlaybackService.loadState(PlaybackService.java:1949)
                    at ch.blinkenlights.android.vanilla.PlaybackService.onCreate(PlaybackService.java:436)
                    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2906)
                    at android.app.ActivityThread.access$1800(ActivityThread.java:169)
                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1506)
                    at android.os.Handler.dispatchMessage(Handler.java:111)
                    at android.os.Looper.loop(Looper.java:194)
                    at android.app.ActivityThread.main(ActivityThread.java:5546)
                    at java.lang.reflect.Method.invoke(Native Method)
                    at java.lang.reflect.Method.invoke(Method.java:372)
                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                 Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                    at libcore.io.Posix.open(Native Method)
                    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                    at libcore.io.IoBridge.open(IoBridge.java:482)
                    at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                    at android.app.ContextImpl.openFileInput(ContextImpl.java:1086) 
                    at android.content.ContextWrapper.openFileInput(ContextWrapper.java:185) 
                    at ch.blinkenlights.android.vanilla.PlaybackService.loadState(PlaybackService.java:1949) 
                    at ch.blinkenlights.android.vanilla.PlaybackService.onCreate(PlaybackService.java:436) 
                    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2906) 
                    at android.app.ActivityThread.access$1800(ActivityThread.java:169) 
                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1506) 
                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                    at android.os.Looper.loop(Looper.java:194) 
                    at android.app.ActivityThread.main(ActivityThread.java:5546) 
                    at java.lang.reflect.Method.invoke(Native Method) 
                    at java.lang.reflect.Method.invoke(Method.java:372) 
                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) `

Full log:

> http://pastebin.com/gEwfKC4h

Additionally, when I open SD Scanner preference page and rotate my phone vertically it throws Fatal Exception:

> http://pastebin.com/me4XJ3Tq

**Comment by adrian-bl** [comment] 2016-11-28 12:29
Thanks:

The FileNotFound exception is 'normal' - it just means that we had no state to restore (which is expected on a fresh install)

> @adrian-bl It seems that no error appears in log, when I press Start scan button, but at program 
> startup "Failed to load state" exception throws:

I just noticed that your music is stored in /storage/sdcard1, so maybe it fails in the next try/catch block: Did you also add some logging there?

> Additionally, when I open SD Scanner preference page and rotate my phone vertically it throws Fatal 
> Exception:

Oh, that's a nice find. But we are getting rid of the sd-scanner soon anyway, so deleting the code will automatically fix this ;-)

**Comment by apikozh** [comment] 2016-11-28 13:30
I add logging to all catches in getScanTargets function and no errors appear. Then I put log print at beginning of getScanTargets and added breakpoint, and I didn't see my log output in log/program didn't reached breakpoint. So maybe this function isn't called?

**Comment by adrian-bl** [comment] 2016-11-28 13:48
Oh, good catch!

I just noticed that

```
onAttach(Context)
```

is an API level 23 function, so it will never get called on Android < 6.x :-O

Could you give this patch a try?
https://gist.github.com/adrian-bl/6ade39da520f1a0d31a4b89003731253

It moves the init-code to onCreate() and gets rid of the onAttach call.

(Totally untested)

**Comment by apikozh** [comment] 2016-11-28 18:41
Yes, SD Scan starts now!
But when I use "medialibrary" branch with this patch it still shows empty library.

> http://pastebin.com/T5VJEBFW

**Comment by adrian-bl** [comment] 2016-11-29 14:30
> Yes, SD Scan starts now!

Ok, great: So i'll add the patch to the master and push a new version to f-droid soon.

> But when I use "medialibrary" branch with this patch it still shows empty library.

That's bad: Could you re-try with the current HEAD of the branch?
Scanning /storage/sdcard1 was only added recently, so your version might not look at this directory. (Note: the library might seem to be empty at the beginning as the medialibrary branch builds the database from scratch)

**Comment by apikozh** [comment] 2016-11-30 03:05
I tried with current HEAD. It works, but partially. After launching the application, library begins to fill with data (SD Scanner starts automatically). Results are following:
- Tabs artists and genres filled as it should be.
- Tabs albums, songs and playlists still empty.

**Comment by nixingizgood** [comment] 2016-11-30 23:37
@adrian-bl 

A bit late to the party here, not sure if this question is still pertinent...

> Are you able to browse /storage/emulated/0 in the files tab? (And: what is the starting point you see there?)

The answer is "no". I only see "legacy" in /storage/emulated. And I am not sure what you mean by starting point.

**Comment by adrian-bl** [comment] 2016-12-01 16:04
> Tabs albums, songs and playlists still empty.

@apikozh thanks for testing this. Hmm, but this is odd: Did you ever uninstall vanilla music before fetching the new medialibrary-head? If not, then you could try to as it might solve the issue: I did some SQL schema changes (and the branch doesn't do SQL updates) recently, so queries for songs and album may just silently fail.

> The answer is "no". I only see "legacy" in /storage/emulated. And I am not sure what you mean by 
> starting point.

@nixingizgood I meant to ask in which folder the 'Files' tab does start.
But i assume that you hit the same bug as apikozh, so the posted patch (included in the next release) should also resolve the issue for you

**Comment by adrian-bl** [comment] 2016-12-02 06:59
I'm going to close this as i pushed the fix to the master branch (https://github.com/vanilla-music/vanilla/commit/d6b8cdbddc75737b31db10e736e3f8e5f312754f).

I also increased the version-code to 10461, so hopefully f-droid will pick it up and start a rebuild

**Closed by adrian-bl** 2016-12-02 06:59 UTC
