### ISSUE TITLE
Sorting should take into account the "disc number" tag

### ISSUE THREAD

**Issue by dror3go** [vanilla-music/vanilla#456] opened 2016-10-27 09:57 UTC
Listening to albums with more than one disc, tagged with the "disc number" results in Vanilla Music sorting the tracks only by the track number, which is not the correct order.

"disc number" tag sort should be added.

**Comment by adrian-bl** [comment] 2016-10-27 15:06
Not sure if we can do much about this: Android does unfortunately not index the disc number, so we can not sort using this information.

But one thing we could try is to sort by album-id + track.
The issue with this is that album-id is 'semi-random' - but at least we would seperate multiple albums

**Comment by dror3go** [comment] 2016-10-27 15:24
@adrian-bl Thanks for the quick answer. However, I find this solution somewhat insufficient, since all discs belong to the same album.

I'm not sure what's _album-id_, but if it's not user-taggable (as in id3 tag) then is it possible to maybe use the _album-id_, but somehow still keep the UI showing the tracks as a single album?
If _album-id_ is user-taggable then I find it a bit weird to require users to add an extra tag to be used for specific software.

What do you think?
How other Android applications handle this issue?

**Comment by adrian-bl** [comment] 2016-10-27 15:36
The UI would not change in anyway: we would just do a 'SORT BY album-id,tracknumber' instead of SORT BY tracknumber'.

The album-id is an android internal index (not related to tagging).

An example: if you add album A, B and C, android will automatically assign an index to these albums.
The index is semi random (so you might get A=2, B=8, C=3) but unique.

Therefore: if we also sort by album-id, we will group albums togegether in the 'Tracks' tab - but the album order might be in the wrong order: so all tracks of album 3 might show up before album 2.

**Comment by dror3go** [comment] 2016-10-27 15:56
Okay, I understand what you mean. Not a perfect solution, but maybe better than the current situation?

BTW, I found this Android bug report: https://code.google.com/p/android/issues/detail?id=1845

**Comment by adrian-bl** [comment] 2016-10-29 18:30
Thanks for the link to the bug report: i just realized that there is indeed nothing we can do about this (i first misunderstood the issue you described).

-> So the issue is that Android combines both disks into a single album id: We therefore have no way to know how to sort, as the required information simply is not available (as described in the bug report).

So until (if ever) this is fixed in android itself, we can not display albums which are tagged like this :-(
One workaround you could try is to split up Disc 1 and 2 into different folders: This *should* cause android to assign different album id's to both disks.

**Comment by dror3go** [comment] 2016-10-29 19:36
Oh damn. What about making the app read the ID3 tags itself, instead of relying on Android to provide that data? I've no idea how the app currently works, and I'd assume this to be quite a big deal, but still - wondering.

**Comment by adrian-bl** [comment] 2016-11-04 19:59
This will be a huge effort but i've created a bug (#460) to at least think about it.

**Comment by adrian-bl** [comment] 2016-12-18 10:03
This feature has been implemented in our 'mediadb' branch (where we implement our own library)

I'm closing this as the mediadb-branch will hopefully soon be merged into the master.

**Closed by adrian-bl** 2016-12-18 10:03 UTC
Labels: project-mediadb

**Comment by dror3go** [comment] 2017-05-16 06:39
@adrian-bl Is that fixed in version 1.0.52? I checked it with a couple of double albums - but the sorting still seems to ignore the disc number.
