### ISSUE TITLE
<No Album> will pick up on embedded cover art of a song, then never ditch/update it if that song is properly updated to be in an album

### ISSUE THREAD

**Issue by JonasT** [vanilla-music/vanilla#903] opened 2019-01-20 21:17 UTC
- Vanilla Music Version (Settings -> About): 1.0.81
- Android Version: 7.1.1
- Phone vendor / model: Gemini PDA
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description
`<No Album>` will pick up on embedded cover art of a song in the no album list (this I find counter-intuitive already, but I can understand the rationale behind it as explained in #619 ), then it will be continuously displayed forever even if I update all the songs that had that embedded cover to be in an album and rescan - and that's now legitimately bugging me, because that means there is no obvious way to fix it / get rid of it again.

## Steps to reproduce the issue

1. Tag a song with a cover that has no album set, and have other songs without cover that have no album set
2. Scan the library such the songs are picked up, verify that `<No Album>`now shows this image
3. Tag all no-album songs that have this cover with a proper album
4. Rescan

 --> all the songs that had that cover are now gone from the `<No Album>` list as expected, but the `<No Album>` list continues to show their cover

**Comment by JonasT** [comment] 2019-01-20 21:34
@andiandi13 makes sense, and that would also solve my problem. I agree that it doesn't make too much sense for `<No Album>` to show a cover anyway, after all it's at best a completely random one

**Comment by andiandi13** [comment] 2019-01-20 21:47
Yeah as I said it's also really disturbing

**Comment by adrian-bl** [comment] 2019-02-17 14:32
Closing as a duplicate of #819 (which is now fixed)

**Closed by adrian-bl** 2019-02-17 14:32 UTC
