### ISSUE TITLE
Resiliance against decoding errors

### ISSUE THREAD

**Issue by nvgtx** [vanilla-music/vanilla#364] opened 2016-05-27 00:35 UTC
For certain flac files playback stops reproducible, the only way to recover is to manually select another track.
The debug log indicates that an decoding error occured in /system/bin/mediaserver, Vanilla Music reacted to this error by stopping playback without any notification.
While it looks like the core problem is in the decoder (and should be fixed too), Vanilla Musics reaction to the error is suboptimal. Instead it would be recommended to select the next track and display a notification regarding the error.

u0_a171   12077 3158  3298560 255372 fg  SyS_epoll_ 0000000000 S     ch.blinkenlights.android.vanilla
media     13386 1     232180 54188 fg  binder_thr 0000000000 S     /system/bin/mediaserver

05-27 00:39:20.157 12077 12077 V MediaPlayer-JNI: getCurrentPosition: 8052 (msec)
05-27 00:39:20.757 13386 15005 E NuPlayerDecoder: err = -1009
05-27 00:39:20.757 13386 15005 E NuPlayerDecoder: Stream error for OMX.SEC.flac.dec (err=-1009), EOS successfully queued
05-27 00:39:20.757 13386 15000 V NuPlayer: decoder audio kWhatError
05-27 00:39:20.757 13386 15000 E NuPlayer: received error(0xfffffc0f) from audio decoder, flushing(0), now shutting down
05-27 00:39:20.757 13386 15004 I NuPlayerRenderer: onPause
05-27 00:39:20.757 13386 15000 V NuPlayer: performDecoderFlush audio=2, video=0
05-27 00:39:20.757 13386 15004 I MediaClock: setPlaybackRate rate : 0.000000
05-27 00:39:20.757 13386 15000 V NuPlayer: [audio] flushDecoder needShutdown=1
05-27 00:39:20.757 13386 15004 V AudioSink: pause
05-27 00:39:20.757 13386 15000 V NuPlayer: msg : 100, ext1 : 1, ext2 : -1009
05-27 00:39:20.757 13386 15000 D NuPlayerDriver: notifyListener_l(0xf118be00), (100, 1, -1009)
05-27 00:39:20.757 13386 15000 V MediaPlayerService: [19] MEDIA_ERROR() ContextAware send information
05-27 00:39:20.757 13386 15000 V MediaPlayerService: [19] notify (0xecf26140, 100, 1, -1009)
05-27 00:39:20.757 12077 12118 V MediaPlayer: message received msg=300, ext1=0, ext2=0
05-27 00:39:20.757 13386 15005 I NuPlayerRenderer: flush audio, notifyComplete 1
05-27 00:39:20.757 13386 15005 D NuPlayerRenderer: signalTimeDiscontinuity() mHasAudio = 1 , mHasVideo = 0
05-27 00:39:20.757 13386 15004 I NuPlayerRenderer: flushing audio
05-27 00:39:20.757 13386 15006 I ACodec  : [OMX.SEC.flac.dec] signalFlush
05-27 00:39:20.757 13386 15004 I NuPlayerRenderer: onFlush mAudioDrainGeneration : 2
05-27 00:39:20.757 13386 15004 V AudioSink: flush
05-27 00:39:20.757 13386 15004 V AudioSink: stop
05-27 00:39:20.757 13386 15006 I ACodec  : [OMX.SEC.flac.dec] ExecutingState flushing now (codec owns 5/5 input, 0/9 output).
05-27 00:39:20.757 13386 15006 I ACodec  : [OMX.SEC.flac.dec] Now Flushing
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] FlushingState onOMXEvent(0,1,0)
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] FlushingState onOMXEvent(0,1,1)
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] Now Executing
05-27 00:39:20.767 13386 15000 V NuPlayer: decoder audio flush completed
05-27 00:39:20.767 12077 12118 V MediaPlayer: Received SEC_MM_PLAYER_CONTEXT_AWARE
05-27 00:39:20.767 12077 12118 V MediaPlayer: callback application
05-27 00:39:20.767 12077 12118 V MediaPlayer: back from callback
05-27 00:39:20.767 13386 15000 V NuPlayer: renderer audio flush completed.
05-27 00:39:20.767 13386 15000 V NuPlayer: initiating audio decoder shutdown
05-27 00:39:20.767 12077 12077 I MediaPlayer: send context aware event
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] Now Executing->Idle
05-27 00:39:20.767 13386 15007 I SEC_BASE_COMP: SEC_OMX_ComponentStateSet: Cur(3) -> Dest(2)
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] Now Idle->Loaded
05-27 00:39:20.767 12077 13255 V MediaPlayer: message received msg=100, ext1=1, ext2=-1009
05-27 00:39:20.767 13386 15007 I SEC_BASE_COMP: SEC_OMX_ComponentStateSet: Cur(2) -> Dest(1)
05-27 00:39:20.767 13386 15006 I ACodec  : [OMX.SEC.flac.dec] Now Loaded
05-27 00:39:20.767 12077 13255 E MediaPlayer: error (1, -1009)
05-27 00:39:20.767 12077 13255 V MediaPlayer: callback application
05-27 00:39:20.767 12077 13255 V MediaPlayer: back from callback
05-27 00:39:20.767 12077 12077 I MediaPlayer: sendBroadcast CONTEXT_AWARE_MUSIC_INFO - type(error) - id (19)
05-27 00:39:20.767 12077 12077 E MediaPlayer: Error (1,-1009)
05-27 00:39:20.767 12077 12077 E VanillaMusic: MediaPlayer error: 1 -1009

[bugreport_essential.txt](https://github.com/vanilla-music/vanilla/files/285567/bugreport_essential.txt)

**Comment by adrian-bl** [comment] 2016-05-27 06:33
We already do something like this if we are unable to read a file, see: https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/PlaybackService.java#L1362

Missing files are a 'temporary' error (= will fix itself after the next media scan), so skipping them makes sense - and we could probably do the same in the onError() handler.

However: Isn't the file causing this error simply broken? Is the reference-flac implementation able to decode the file without any errors?

**Comment by nvgtx** [comment] 2016-05-27 07:51
The error happens with 3 different files which work fine when played under Android 4.4, Linux, Windows by any given player...
Under Android 6.0.1 this error happens so I think the decoder is having some kind of problem with the encoding of the file.
Nonetheless what is really annoying, is that the playback simply freezes.
In the log, the playback of the file works fine initially - until 0:08 then it stops and that's it.

**Comment by adrian-bl** [comment] 2016-05-27 08:17
Could you send me such a file via e-mail to adrian@blinkenlights.ch ?
Having such a broken file would help to validate that the fix actually works ;-)
(we might have to do some magic to get the media player automatically back into the correct state)

**Comment by nvgtx** [comment] 2016-05-27 08:47
mail sent

**Comment by adrian-bl** [comment] 2016-05-27 17:34
thanks: i got them. Will have a look at it next week.

**Comment by adrian-bl** [comment] 2016-06-05 08:14
I tested this on my Nexus 5 running Android 6 and i'm unable to trigger the error - i even tried to corrupt parts of the file but the playback either fully stops (without a media player error) or it just skips parts of the file.

But i hacked up a patch for this: https://gist.githubusercontent.com/adrian-bl/cf0ce671d400393dcba6e5b33c8557d9/raw/5ee513bde96b9b9da8945acb002ccaa7db590200/gistfile1.txt could you give it a try to see if it solves the issue on your phone?

**Comment by nvgtx** [comment] 2016-06-05 21:45
Ok, now I've finally managed to build it. ;-)
Well, skipping works somehow but is unstable. Sometimes playback continues correctly, more often it stops. Furthermore, once the VanillaMusic process crashed while skipping (sadly not logged)...

**Comment by adrian-bl** [comment] 2016-06-18 09:09
Hmm, ok: This might be due to the fact that the media player didn't set the error flag.
Could you please give this patch a try?: https://gist.github.com/adrian-bl/8b2bf80d477c826bc795bd07c4c51bc6

The only difference between the other version is, that we force the error flag to be set after the media player failed.

**Comment by nvgtx** [comment] 2016-06-20 19:27
That particular part seems to work fine (except for the abort condition where I doubt whether that logic-OR is correct).

The problem seems to be, that the MSG_CALL_GO message during handling MSG_SKIP_BROKEN_SONG is sometimes not having any effect.
Perhaps a race condition between the shutting down media-player and updating the FLAG_PLAYING? setting FLAG_PLAYING before MSG_CALL_GO improved the chances of continued playback to about 80%.

**Comment by adrian-bl** [comment] 2016-06-20 19:59
> (except for the abort condition where I doubt whether that logic-OR is correct).

Which line/logic do you mean exactly?

> Perhaps a race condition between the shutting down media-player and updating the FLAG_PLAYING? 

Well, your media player seems to be in an undefined state, so i'm not that surprised about a random outcome :-)

> setting FLAG_PLAYING before MSG_CALL_GO improved the chances of continued playback to about 80%.

So you did call 'setFlag(FLAG_PLAYING); ?
That would be odd, as calling MSG_CALL_GO in this state (eg: flag_playing set) would cause us to PAUSE the media player.

**Comment by nvgtx** [comment] 2016-06-20 20:34
> Which line/logic do you mean exactly?
if(mTimeline.isEndOfQueue() == false && getSong(1) != null && (playing || (mSkipBroken > 0 && mSkipBroken < 10)))
I don't know whether if its correct or not - it just looks weird to have an variable which could override the counter entirely.

> So you did call 'setFlag(FLAG_PLAYING); ?
Yes, given that it stops nearly always (The UI also switches to paused) - why not trying... As I said, it then works nearly always. That's why I'm suspecting some kind of desync...

**Comment by adrian-bl** [comment] 2016-06-23 18:32
> I don't know whether if its correct or not - it just looks weird to have an variable which could override the 
counter entirely.

The logic behind this is, that we only try to skip to a new song if we either just detected the error (eg playing is true) or we are already in skip mode (mSkipBroken > 0)

> That's why I'm suspecting some kind of desync...

Yes, maybe there is some other event coming in later.
Unfortunately, this is almost impossible to debug for me as i have no device where i can reproduce the error :-/

**Comment by adrian-bl** [comment] 2016-08-05 10:13
Closing this as i am unable to reproduce the crash on 4 different devices

**Closed by adrian-bl** 2016-08-05 10:13 UTC
Labels: enhancement, patches-welcome
