### ISSUE TITLE
Cannot play directory since 1.0.47

### ISSUE THREAD

**Issue by Stevko-sk** [vanilla-music/vanilla#518] opened 2017-01-19 10:31 UTC
On Files tab when I select a folder (hold finger on it) and then choose Play in the menu that pops up, I get 0 tracks playing.

Later I found out that after scan (this seems to be a new thing which took forever) some folders do play and some do not.

**Comment by adrian-bl** [comment] 2017-01-19 17:10
This is most likely related to #517 

Do the 'not playing files' have something in common? eg: no tags or all of them are M4A / FLAC / Whatever files?

**Comment by adrian-bl** [comment] 2017-01-29 15:04
Closing this as a duplicate of #517

**Closed by adrian-bl** 2017-01-29 15:04 UTC
