### ISSUE TITLE
Library screen behaves differently with "artist" and "album artist" as the first tab

### ISSUE THREAD

**Issue by sergey-protserov** [vanilla-music/vanilla#659] opened 2017-08-26 18:12 UTC
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 7.0
- Phone vendor / model: Honor (Huawei)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

If I have "Artist" as the first tab in the library screen that's how the library browser works:
1. I am on the Artist tab, I tap on the Artist's name.
2. I am on the Album tab, I see all the albums belonging to the Artist. I tap on the Album's name.
3. I am on the Track tab, I see all the tracks belongning to the Album. If I tap "Back" once I get to the Album list and see all the albums belonging to the Artist. If I tap "Back" once more I get back to the Artist list.
If I have "Album Artist" as the first tab in the library screen, I get to the Track tab just as in steps 1, 2, and when I tap "Back" once I get back to the Album tab and see all the albums belonging to the Album Artist, BUT if I tap "Back" once more, I do not get back to the Album Artist tab, instead I remain on the Album tab and see ALL the Albums in the library. One more "Back" brings me to the home screen (exiting Vanilla).
## Steps to reproduce the issue

See above.

## Screenshot / Video (If applicable)

https://sendvid.com/sl0cxd5d
On this video I begin from the Album Artist tab, click on the "Black Tape for a Blue Girl" Album Artist, then choose "As one aflame laid bare by desire" album, and then tap "Back" thrice: first tap brings me to the Album tab, the second one keeps me on the Album tab, but now I see all the albums, not only "Black tape for a blue girl"'s, third tap exits Vanilla.

**Comment by adrian-bl** [comment] 2017-09-03 13:01
That's because the limiter (= the grey filter) doesn't really inherit from your previous selection:

Selecting an album will always add a filter for the primary_artist of the selected album, no matter where you were before. Hitting BACK always drops one limiter, so you will eventually end up with an ALBUM filter instead of an ALBUM_ARTIST filter.


I'm going to close this as a duplicate of #663 as both seem to have the same root cause of confusion.

**Closed by adrian-bl** 2017-09-03 13:01 UTC
Labels: album-artist
