### ISSUE TITLE
Setting of music-folder (excluding other audio)

### ISSUE THREAD

**Issue by github-user-1** [vanilla-music/vanilla#545] opened 2017-02-12 18:18 UTC
Please excuse if I missed the option somewhere but I searched around and could not find where I can explicitely set (or explicitely remove) forders with audio-files.

Reasoning: I have e.g. music as well as audiobooks, podcasts, voice recordings, language courses, etc. stored on my phone. With this player I want to listen (and see listed) music files only and I do have a separate folder for this. If this can't be set I think it's worth providing that option (just like VLC but that one is not updated on F-Droid for the time being anymore).

**Comment by adrian-bl** [comment] 2017-02-12 18:44
We already have a bug open for this: i am closing this issue as a duplicate of #22

**Closed** 2017-02-12 18:44 UTC
Labels: duplicate
