### ISSUE TITLE
confirmation dialog before changing queue.

### ISSUE THREAD

**Issue by sk280** [vanilla-music/vanilla#129] opened 2015-01-03 23:18 UTC
Feature request:
1. Can a yes/no confirmation dialog be displayed (option in settings to enable, disabled by default) when queue is suddenly cleared (mostly by accident)? 
Reason: 
1. I start from a blank playlist, no files playing. I scroll through files and enqueue them to the queue by long pressing them and choosing enqueue. 

My current list action is: enqueue if playing or play if paused. Sometimes I accidentally play the file due to a missed long click resulting in the current file being played and thus discarding the entire queue I had just assembled. 

My use case:
1. New setting to display confirmation when current queue has files (dirty) and is about to be cleared by use selecting a file or playlist to play. 
2. If setting enabled, display confirmation dialog "Your playback queue will be cleared. Proceed?"
Having an optional confirmation dialog displayed when the queue is dirty (modified like a file save dialog for modified files) would really help. It can be disabled by default and only enabled by user.
3. New setting can be added to either a new menu item in settings called: Queue management or to miscellaneous features menu.

**Comment by adrian-bl** [comment] 2017-12-03 14:00
I think we should rather have an undo function.

Closing as duplicate of #454

**Closed by adrian-bl** 2017-12-03 14:00 UTC
Labels: request
