### ISSUE TITLE
External playlists not recognized

### ISSUE THREAD

**Issue by bbaserdem** [vanilla-music/vanilla#722] opened 2018-01-29 11:00 UTC
- Vanilla Music Version (Settings -> About): 1.0.58
- Android Version: 7.0 
- Phone vendor / model: SAMSUNG-SM-G930A (Galaxy S7)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.
...

## Description
I have m3u files in my media library and they are not being loaded into playlists.

I am not sure if this is a bug or a feature request. Or if my m3u files are not compatible. Every other music player I tried seems to recognize the playlists just fine.
....

## Steps to reproduce the issue
* Set a directory `*/Music` as the only media folder.
* Have m3u playlist in that folder

**Comment by andiandi13** [comment] 2018-01-29 11:06
Did you do a manual scan of your media library in settings ?
Vanilla should import playlists as soon as they are imported to android internal library.

More info here : https://github.com/vanilla-music/vanilla-music.github.io/wiki/FAQ#playlists-management

**Comment by bbaserdem** [comment] 2018-01-29 12:00
Thank you, I guessed I glossed over the part in tho FAQ. However, it is not helping. I did a library scan with flushintg database. My playlists still arent there. I don't have a stock music player on my phone so I dont know how I can create them in the system library.

**Comment by andiandi13** [comment] 2018-01-29 12:10
Well if you have not any stock music player I suggest you download this playlist backup app :

https://play.google.com/store/apps/details?id=org.ssi.playlistbackup

You can check what playlists exist into your stock library and also import m3u to android (and so to vanilla)

**Comment by andiandi13** [comment] 2018-01-29 19:30
You can choose any path with the app, even in Android/data folder.
Import Playlist>Advanced>Select File.

But if your playlists are in the system, its strange that Vanilla don't show them

**Comment by bbaserdem** [comment] 2018-01-30 22:03
So I am using the external app, but my playlists still are not appearing. I did the update with flushing the database multiple times, but it's not working.

From what I have read, even if I get it working, if I edit the m3u playlists they wont be updated? (Thats how I do it, I keep the files between my computer and phone synced and would edit playlists on my computer) I have to do a full library scan each time I want to sync tnhe playlists? That seems pretty problematic if I get it right.

**Comment by adrian-bl** [comment] 2018-02-03 16:46
Vanilla Music can only import playlists which Android itself already imported - we do not have our own m3u parsing code.

Closing this as a duplicate of #643 which deals with m3u parsing.

**Closed by adrian-bl** 2018-02-03 16:46 UTC
