### ISSUE TITLE
Force Library Reset from Settings

### ISSUE THREAD

**Issue by IAmThePan** [vanilla-music/vanilla#312] opened 2016-03-28 20:24 UTC
Sometimes I want to force a reset for my music library.

For example, 
- Genres don't disappear when I remove songs from my phone.
- Songs don't show up after I add them.
- If I search in the Files tab, I can find songs I have deleted in the `storage/emulated` directory

**Comment by adrian-bl** [comment] 2016-03-29 15:43
The Genres issue will be fixed in the next release, but i agree that it would be nice to have a way to trigger a rescan.

We could probably re-use code from 'SD-Card Scanner' which works fine on 5.x and 6.x

**Comment by xbao** [comment] 2016-06-12 04:06
@adrian-bl I added the SD Scanner sources from https://github.com/jerickson314/sdscanner to the preferences screen: 

https://github.com/vanilla-music/vanilla/compare/master...xbao:sdscanner

The source is mostly unchanged apart from needing to convert the SD Scanner MainActivity into a fragment (SDScannerFragment) so that it integrated with the preferences screen. 

I haven't had time to test it thoroughly, but for simple use it seems to work. If you're happy with the approach I'll open a PR and we can discuss it there

**Comment by adrian-bl** [comment] 2016-06-12 11:52
Looks good to me, feel free to create a PR, i'll then also give it a go :-)

One thing we should do for sure is to hide the option on devices running Android <= 4.3 (we are doing something similar for the themes in https://github.com/vanilla-music/vanilla/commit/f323ab24d2d640ed6a29328ccfe03f3c1dcb8054) (if i'm not mistaken, SD-Scanner requires 4.4)

Another thing is the UI: A dropdown with common paths would be much nicer (or a file chooser), but this can wait after it hit the master branch :-)

**Comment by xbao** [comment] 2016-06-12 12:27
> if i'm not mistaken, SD-Scanner requires 4.4

I thought so too, but the minimum SDK seems to be 14 (ICS): https://github.com/jerickson314/sdscanner/blob/master/AndroidManifest.xml#L6. Perhaps the 'compatible with 4.4' comments in the source/readme mean that it works with the SD card permission changes that came with 4.4. I'll try it out on some of the older test devices we have at work. 

> A dropdown with common paths would be much nicer (or a file chooser)

Completely agree, maybe a dropdown with the paths of the external storages and a '...' option to open a file chooser. 

> but this can wait after it hit the master branch :-)

Also agree :)

PR #377

**Comment by adrian-bl** [comment] 2016-06-12 14:26
Thanks, i merged the PR and kicked on an (early) nightly build.
Please note that i'm mostly offline next week, but i'll give it a test drive on my phone :-)

**Comment by xbao** [comment] 2016-06-13 03:44
Sure, let me know how it goes. I likely won't be able to work on it until the weekend anyway, so no rush.

**Comment by adrian-bl** [comment] 2016-06-18 09:29
Ok, i played with this and it seems to work pretty well:

Two things (apart from the UI) i noticed are:

* Using the library during the scan is tricky as the list view tends to scroll back to element 0. Of course, this is not related to the new code and was always an issue. I created #382 to track this

* Re-entering the SD-Scanner during a scan causes the UI to show no progress as the fragment gets re-created on every onCreate() call. (findFragmentByTag returns null).
Setting mScanFragment to be static and only call findFragmentByTag if it is null would solve the issue - but i'm not sure how hacky this approach is ;-)

**Comment by andiandi13** [comment] 2016-06-18 13:05
@adrian-bl I've tested the SD Scanner in the nightly build but there's is something odd, when I scan a folder (/Storage here) it delete EVERY playlist that I created manually but don't erase those who come from .m3u files :/

**Comment by adrian-bl** [comment] 2016-06-18 14:26
That would be very odd: what version of Android are you using?

**Comment by andiandi13** [comment] 2016-06-18 15:11
I'm running on JellyBean 4.1.2.

The oddest is that when I create playlists with certains songs, the playlist WON'T delete, but with others it will, I completely don't understand

**Comment by xbao** [comment] 2016-06-19 01:04
@andiandi13 That's very, very unexpected, I'll try and reproduce it now. Is there any difference between the songs that 'protect' the playlist and those that don't? Storage location for example? Inclusion in any of the .m3u backed playlists? Sorry your playlists got deleted, I had to remake mine recently and it was a PITA :(

@adrian-bl Hah, I didn't realise the scan would continue when you navigate away from the screen :) It's probably best if we don't have background processing tied to Activity/Fragments, as it causes bugs like the ones you've noticed. I'm thinking I cancel the scan when the user navigates away, or move the scanning to background service that the activity controls and queries

**Comment by andiandi13** [comment] 2016-06-19 01:11
@xbao I tried to figure it out, and no, with two songs from the same location one playlist is deleted, the other isnt, and of course iif both are in a playlist it won't be deleted, since there is a song that "protect" the playlist as you say.

I also compared the file size, the filename length, the fact that there is/isn't a cover but without success ..

**Comment by xbao** [comment] 2016-06-19 02:32
@andiandi13 Thanks for that, I managed to reproduce it a few times on the 4.1.2 x86 emulator, but very inconsistently. Does it happen every time on your device?

**Comment by andiandi13** [comment] 2016-06-19 02:42
@xbao It really depends on which songs are in the playlist but in my case when I choose a song among my 400+ files, I'd say that 70% of the time the scan erase the playlist.

**Comment by xbao** [comment] 2016-06-19 05:30
I've pushed a work-around in commit 0736bc54b008f5 to master, it will be in the next nightly. @andiandi13 could you please try it out and let me know how it goes?

The workaround is to not process MediaStore db entries that have a size of '0', which all non-file backed playlists do. Hopefully it won't have any side-effects. The only other entries my phone has with size 0 are cached thumbnails.

As for the cause, it appears to be that the MediaStore gives the filename of non-file backed playlists as `<sdcard>/Playlists/<playlist_name>`, which don't exist on the file system. When that path gets passed to [/MediaScannerConnection.html#scanFile](https://developer.android.com/reference/android/media/MediaScannerConnection.html#scanFile(android.content.Context,%20java.lang.String[],%20java.lang.String[],%20android.media.MediaScannerConnection.OnScanCompletedListener)) on (at least) OSv4.1, the playlist is removed from the MediaStore. On OSv5.1+ it does not, so I'm guessing it was a bug that got fixed at some point.

**Comment by andiandi13** [comment] 2016-06-19 11:38
@xbao I see.. I don't know how to use the java file though (I'm not good at compiling, I guess)

**Comment by adrian-bl** [comment] 2016-06-19 11:49
@andiandi13 you don't have to compile it yourself: We provide 'nightly builds' (eg: the compiled git-master is rebuilt every 24 hours).

You can download a precompiled version at http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk (this build already includes xbao's changes).

You can install it alongside with vanilla music: The nightly build will show up as 'Vanilla Nightly'

**Comment by andiandi13** [comment] 2016-06-19 11:58
@adrian-bl Thank you

@xbao It work like a charm, none of my playlist are deleted anymore ! thank you very much :)

**Comment by xbao** [comment] 2016-06-21 11:23
@andiandi13 Yes, sorry I should have been clearer. Glad you got the changes and they're working for you, thanks for the feedback!

**Comment by adrian-bl** [comment] 2016-07-17 15:53
Closing this as the required code has been merged.

Thanks to @xbao for fixing this issue!

**Closed by adrian-bl** 2016-07-17 15:53 UTC
Labels: enhancement, patches-welcome, request
