### ISSUE TITLE
Headset button becomes unresponsive after some time

### ISSUE THREAD

**Issue by K-RAD** [vanilla-music/vanilla#96] opened 2014-09-05 18:07 UTC
Running on an S4 with Android 4.3. 

Typically, when I have a music app playing in the background, it also shows a small widget by default on my lockscreen and the media button on my headset works for stop/play/next. 

After some time with vanilla playing in the background, it stops showing on the lock screen and the media button stops working completely. I have to unlock the phone and open the app to start working again. 

I saw the same behavior with a different app (Poweramp), though it doesn't happen with the samsung music player or google play music.

**Comment by adrian-bl** [comment] 2015-10-09 18:56
Closing this ad a duplicate of #223.
(Probably caused by the unregister call in onDestroy())

**Closed by adrian-bl** 2015-10-09 18:56 UTC
