### ISSUE TITLE
HUGE delay between hitting play and music start

### ISSUE THREAD

**Issue by Pastafarianist** [vanilla-music/vanilla#67] opened 2014-01-20 19:48 UTC
I have about 2 000 tracks in my music library on my device, and the first time I saw this bug was when the number of tracks exceeded 2 000. There does not seem to be a fixed pattern to reproduce it, it appears randomly without any changes to the library (i.e. no new tracks are added).
The symptoms are: there is a HUGE delay between changing the current playback and the changes taking effect. More than a minute. This applies to pausing/resuming, navigating to the previous/next track, changing the playlist entirely (setting it to the entire library / specific artist / specific track).

**Comment by adrian-bl** [comment] 2015-08-14 07:53
Closing this old bug as nobody seems to be able to reproduce it:
I have 1'600 songs on my devices (same library shared across multiple android devices using syncthing) and do not have any performance issues.

**Closed by adrian-bl** 2015-08-14 07:53 UTC

**Comment by Pastafarianist** [comment] 2015-08-24 19:31
I had this issue on my previous phone, and now I have the same model but a different device with a different SD card. There are no problems. I guess the old SD card was to blame.
