### ISSUE TITLE
Complilation Albums List More Than Once in Album Tab

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#161] opened 2015-04-16 15:11 UTC
Now I'm yet to encounter a music player that DOESN'T do this so hopefully you guys can figure it out.
When you have a compilation album in your phone, like a movie soundtrack, or something like a studio compilation,or top hits collection, that has more than one artist in the album, that album will be listed more than once in the Albums tab,according how many different artists are in said album.
It would be awesome if the Albums tab detected duplicate album  titles and did a merge. That way,in the Albums tab,and only there,the album would show up in full,as one entry,like it should. 
Even my desktop player on PC has this issue,so it might not be fixable, just sharing a request.

**Comment by PanderMusubi** [comment] 2016-08-12 11:02
This is duplicate of https://github.com/vanilla-music/vanilla/issues/92

**Comment by adrian-bl** [comment] 2017-01-28 13:33
Is this still an issue?

Id expect that this was fixed with the new media db

**Comment by Allanitomwesh** [comment] 2017-01-28 14:14
Hi, on the latest Vanilla this is fixed. 
Confirmed with Suicide Squad OST (various artists)

**Comment by adrian-bl** [comment] 2017-01-28 17:43
Ok, thanks for confirming this!

**Closed** 2017-01-28 17:44 UTC
Labels: project-mediadb, request
