### ISSUE TITLE
Deleting media from external SD card fails on Samsung devices, Android 7 & 8

### ISSUE THREAD

**Issue by eggsgent** [vanilla-music/vanilla#733] opened 2018-02-22 10:27 UTC
Vanilla Music Version (Settings -> About): 1.0.59
Android Version: Android 7, 8

Phone vendor / model: Samsung Galaxy A8, Samsung Galaxy S8 G950F

## Description
Deleting media from external SD card fails on Samsung devices, Android 7 & 8
....

## Steps to reproduce the issue
1. Insert SD card with some files that will be scanned and added to Vanilla Music
2. In Artist view (or other views), select context menu of the entry and select Delete action

Expected result: the files to be deleted from external SD cards
Actual result: Toast saying "0 tracks deleted. Deleting from internal storage works for me.
[deleting_of_media_from_external_SD_card_fail.zip](https://github.com/vanilla-music/vanilla/files/1747487/deleting_of_media_from_external_SD_card_fail.zip)

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment] 2018-04-22 13:57
That's most likely due to lack of SAF support, so this is a duplicate of bug #691

**Closed by adrian-bl** 2018-04-22 13:57 UTC

**Comment by eggsgent** [comment] 2018-04-22 16:58
Does it mean that it fails on all devices which support SD-cards running a certain Android version? My issue is with the regular SD-card slot, not OTG storage.

**Comment by adrian-bl** [comment] 2018-04-25 18:50
It depends on the firmware: Since Android 7 (?), some vendors do not grant any write access to the sdcard using normal file operations - while some other vendors still grant the permission to the app if requested.

But in both cases, RW access can be requested by using SAF.
