### ISSUE TITLE
Album view sort "By Title" broken, makes two separate alphabetical

### ISSUE THREAD

**Issue by JonasT** [vanilla-music/vanilla#897] opened 2019-01-14 19:57 UTC
Album view's sorting "By Title" is broken for me since recently (a month or so), it makes two separate alphabetical lists with a certain whatever subset A-Z first, then it jumps back to A and has another long list A-Z. This is pretty inconvenient because now I always need to look in two places to find something. This started to happen when I scanned for new media at some point with the new media suddenly forming on top as separate list, but even "Flush media database" hasn't ever fixed this and the second list only has started to grow longer.

- Vanilla Music Version (Settings -> About): 1.0.80 Released Nov, 17 2018
- Android Version: Android 7.1.1
- Phone vendor / model: Gemini PDA
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Steps to reproduce the issue

Really not sure, this just randomly started happening at some point when new media was added

**Comment by adrian-bl** [comment] 2019-01-14 20:50
Can you go to Settings > Media Library > (menu) > Dump database and upload the file somewhere?

(The file contains the metadata of your media library (tags and playlists)).

Did you change the language on your phone at some point?

**Comment by JonasT** [comment] 2019-01-19 23:12
@ language: not that I know of, but clearing the app data fixed it. I wonder though, I remember this starting around the time I did a "Flush database" scan, but I recall being surprised that the list of titles wouldn't actually clear out (and starting at roughly that time, new entries would show up separately). Maybe the flushing is broken sometimes and that caused it?

**Comment by adrian-bl** [comment] 2019-01-21 18:41
The library is only updated after the scan finished, so it is normal that you'll still see the old database during a flush.

If flushing didn't fix the issue, then this is very likely related to a language change: We should rebuild our sorting-key if this happens.

**Comment by JonasT** [comment] 2019-01-21 18:58
@adrian-bl the old entries never disappeared though. and I am 99% certain i didn't change the language, I don't even know how to do that

I remember in some older version, the entries disappeared right at the start, which I found more intuitive (also then it's immediately obvious the flushing worked, whereas with the current behavior it kinda leaves you guessing). How about going back to that behavior maybe?

**Comment by adrian-bl** [comment] 2019-02-02 08:38
Having the library constantly updating during a scan made it impossible to scroll while the scanner was running on some android versions, so i'd prefer to keep this as it is.

Closing this issue as we don't have a DB dump, but i suppose that it is very similar to #889 (might not have the same root cause, but rebuilding the search index should have also fixed this issue)

**Closed** 2019-02-02 08:38 UTC
