### ISSUE TITLE
[Feature Request] Please translate Genre numbers to their names

### ISSUE THREAD

**Issue by Mannshoch** [vanilla-music/vanilla#531] opened 2017-02-01 14:43 UTC
Please translate Genre numbers to their names
See also: https://web.archive.org/web/20150315204422/http://axon.cs.byu.edu/~adam/gatheredinfo/organizedtables/musicgenrelist.php

![screenshot_2017-02-01-14-40-42](https://cloud.githubusercontent.com/assets/7795891/22511190/1fba6d5c-e895-11e6-81f4-4ab5a93d99ff.png)

**Comment by adrian-bl** [comment] 2017-02-01 20:58
What version are you running?

This should be fixed in 1.0.48 - maybe a full rescan would help?

**Comment by Mannshoch** [comment] 2017-02-02 10:40
I run 1.0.48 from f-droid.
I did a full rescan.

The attached [.mp3](http://www.hoerspielprojekt.de/audio/dark-space-2046-folge-2-2-wunden/) (CC License) appears in Genre 255 and Hörspiel.

[03 - Ich bin Ina Bruuenning.zip](https://github.com/vanilla-music/vanilla/files/747268/03.-.Ich.bin.Ina.Bruuenning.zip)

**Comment by adrian-bl** [comment] 2017-02-02 17:51
This works for me: The file gets correctly indexed as Genre = Hörspiele using the ID3v2 tag which should get preferred by the os.

Also Genres like '31' should never show up *if* they came from an MP3 file as we translate these: https://github.com/vanilla-music/vanilla/commit/1982b0f969c3c47c2cfde0d7ae728d1d3d9c00bd - so either these were non-mp3 files or the rescan was aborted.

**Comment by Mannshoch** [comment] 2017-02-02 23:31
I deleted all data from the app Media database and checked if the File "03 - Ich bin Ina Bruuenning.mp3" exist a second Time. I was not able to find any. And after rescan I got again a genre 255 with this file. 
I'ts strange because a genre 255 not exist in ID3v1. This appearance as genre 255 and genre Hörspiel exist for the whole "Dark Space" Audioplay and for nine other Audioplays to.

the other numbers in my genre list are equal to their second genre as it is described for IDv3.

**Comment by adrian-bl** [comment] 2017-02-04 11:39
Something seems to be very odd with the ID3 tag reader on your device.

The latest nightly version (See: http://vanillamusic.io/#nightly-builds - you can install it alongside the normal version) has an option to use our own non-android tag reader for MP3 files (Settings > Media Library > Always use builtin tagreader)

This should hopefully fix the issue on your device.

**Comment by adrian-bl** [comment] 2017-02-07 20:32
Closing this issue as i believe that it is fixed in the latest nightly build (note that we are now also 'translating' numeric genres for ANY filetype).

Feel free to re-open if the issue is still present

**Closed by adrian-bl** 2017-02-07 20:32 UTC

**Comment by PanderMusubi** [comment] 2017-04-05 10:17
I am still experiencing this, only genre number is in between brackets such as `(10)` and `(14)`

**Comment by adrian-bl** [comment] 2017-04-05 20:28
If you see anything like '($digit)', then exactly this *string* was stored in the MP3 file - and we will display it as it is.

**Comment by PanderMusubi** [comment] 2017-04-06 11:24
Do you mean that easytag stored genre digits as string and not as integer?

This was working properly before for me. Might be that I was storing ID3 wrong. I used easytag with default settings. Sorry for the extra questions, I hope that this might also help other users with the same problem.

Easytag offers "Use text-only genre in ID3v2 tags". I will test all combinations and report back here the result.

PS   ID3 lib is not supporting 2.4 tags. Trying to get project maintainers motivated to start supporting that. But that is another story.

**Comment by adrian-bl** [comment] 2017-04-06 16:52
Yes.

ID3v1 stores genres as ints, v2 as strings.

If the string is set to "(40)", we will use " (40)" as genre.

**Comment by Mannshoch** [comment] 2017-04-06 20:52
Could you change to read ID3v2.4 instead v1?

**Comment by PanderMusubi** [comment] 2017-04-11 10:21
I am testing now with these settings in easytag:

![screenshot from 2017-04-11 12-13-55](https://cloud.githubusercontent.com/assets/198964/24904597/3e28e3a2-1eb1-11e7-9ea2-4509bb888d95.png)

Are these the best/recommended settings to use?

**Comment by trmendes** [comment] 2017-04-16 17:08
I'm running Vanilla 1.0.51 and I still having problems with the ID3 reading. Many of my genres is being showed as numbers in Vanilla and if I try with another app that other app will show me the string instead of a number.

**Comment by adrian-bl** [comment] 2017-04-16 20:52
Go to settings > media library, tick 'flush database' and start a rescan.

**Comment by trmendes** [comment] 2017-04-16 21:47
@adrian-bl did it like you said but still the same. I still have numbers on my genres tab.

**Comment by adrian-bl** [comment] 2017-04-17 05:07
Are these plain numbers or is there other text? (Screenshot would help)

**Comment by trmendes** [comment] 2017-04-17 11:40
I have tried with the "built in tag reader" on and off and both cases I get the numbers.

![tmp_23579-screenshot_20170417-06333947949948](https://cloud.githubusercontent.com/assets/16507629/25087982/7c461688-2338-11e7-90cb-6017e2306910.png)

![tmp_23579-screenshot_20170417-0633301993332122](https://cloud.githubusercontent.com/assets/16507629/25087991/8aca8540-2338-11e7-8581-eab335381379.png)

![tmp_23579-screenshot_20170417-063317712469622](https://cloud.githubusercontent.com/assets/16507629/25087997/96bac7f2-2338-11e7-9e76-f8c65cfc888f.png)

![tmp_23579-screenshot_20170417-063312346037633](https://cloud.githubusercontent.com/assets/16507629/25088006/9ecf57e6-2338-11e7-90a5-6e60aef4496a.png)

My vanilla apk comes from the f-droid repository

**Comment by adrian-bl** [comment] 2017-04-17 13:26
Please read https://github.com/vanilla-music/vanilla/issues/531#issuecomment-292236161

Your MP3 contains the STRING (24), thats why we display it as it is.

Tag your files correctly and they will show up as they should. (eg: use picard which can automatically tag your files)

**Comment by trmendes** [comment] 2017-04-17 14:01
I can't try Picard right now cause I have no computer with me but I have been checking other apps and they show the right genres without the numbers (same mp3s files) as the screenshot can show you.

![tmp_32227-screenshot_20170417-085534305058760](https://cloud.githubusercontent.com/assets/16507629/25090962/06a79596-234c-11e7-8588-c5e9f01783ee.png)
![tmp_32227-screenshot_20170417-085530666798445](https://cloud.githubusercontent.com/assets/16507629/25090974/0f6b364c-234c-11e7-9023-bed5f1fb16b1.png)
![tmp_32227-screenshot_20170417-085525240138466](https://cloud.githubusercontent.com/assets/16507629/25090979/18278b28-234c-11e7-8ca1-d44652490323.png)

![tmp_32227-screenshot_20170417-085517392037649](https://cloud.githubusercontent.com/assets/16507629/25090985/23c4847c-234c-11e7-8359-f793bc3039e4.png)

I tried an android app to fix the id3 and this app does not show me a number but it shows me the right renger as a string (not a number as a string but 'blues', 'rock', 'etc')

**Comment by adrian-bl** [comment] 2017-04-17 14:05
> I can't try Picard right now cause I have no computer with me but I have been checking other apps and 
> they show the right genres without the numbers (same mp3s files)

This app uses the android Media DB and android does some more 'guessing' on what a genre number looks like (and often gets things wrong by guessing.).

We only assume numeric genres if the genre is a plain number. If the genre is set to a string such as "(20)" (as in your case), we will display the string as "(20)").

**Comment by trmendes** [comment] 2017-04-17 14:12
Got it...thanks... I'll try to find myself a computer and fix my mp3s
