### ISSUE TITLE
Fails to move to next song when playing files in large directories

### ISSUE THREAD

**Issue by stromcooper** [vanilla-music/vanilla#98] opened 2014-09-19 13:06 UTC
I have a few directories with >100 files each in them.  When I long-press the directory, select Play, the first song plays back fine, however the player will not automatically move along to the next song.  I can press the "forward" button and the next song plays, but automatic progression fails.

This does not occur on directories with very few files (~15).  Any ideas?

Running Vanilla 0.9.26 on Android 4.4.4, Slim-4.4.4.build.7.9-weekly-6365 to be specific.

**Comment by xbao** [comment] 2015-08-23 01:29
I'm unable to reproduce on a Moto G2, Android 5.1.1 (Paranoid Android 20150704 build). Folder has 119 tracks. Vanilla 1.0.31

**Comment by adrian-bl** [comment] 2015-10-05 19:30
Closing this bug as i'm unable to reproduce it on 3 devices

**Closed by adrian-bl** 2015-10-05 19:30 UTC
Labels: bug
