### ISSUE TITLE
"Clear queue" only clears up to the current song

### ISSUE THREAD

**Issue by beamer145** [vanilla-music/vanilla#149] opened 2015-03-23 12:52 UTC
When eg 1500 songs are in  the queue and currently song 762 is active (playing or paused), and you select clear queue then only songs 763 till 1500 are removed from the queue.
This is also seems to make it impossible to completely clear the queue since you always keep at least 1 song (unless there is an option to "unselect" all songs I haven't found yet)

Vaguely related remark: if you have >999 songs in the queue, the total number is not shown anymore (shows egg 672/... io 672/1500)

**Comment by aminb** [comment] 2015-03-23 18:08
This is a duplicate of #95

**Comment by adrian-bl** [comment] 2015-03-23 18:36
This is the expected behaviour - maybe we should rename the function but it works as designed.

**Comment by aminb** [comment] 2015-03-24 12:25
I'm proposing we rename the current Clear queue to **Dequeue next songs**, and add an **Empty queue** that does what everyone is asking (clear out the whole queue).

**Comment by adrian-bl** [comment] 2015-03-24 12:50
IMO, a pure empty queue option doesn't make much sense: If you want to use a fresh start, just hit the 'Play' option in the library - the options dropdown is already way too big

**Comment by aminb** [comment] 2015-03-25 00:39
@adrian-bl I agree that the options dropdown in the Now Playing screen is already pretty big, but i still believe having an "Empty queue" would be nice. We could have it in the options menu for the *Queue* activity (which shows up when you click "Show queue" in Now Playing.

**Comment by Allanitomwesh** [comment] 2015-03-25 04:27
"just hit the play option in the library"
How to do this? And does it achieve the sane effect as clearing the whole queue? I personally think clear queue should work as advertised and wipe the slate clean. Currently I have to
1. Go to show queue
2. Play the first track on the queue
3. Then select clear queue
4. Then toss the playing track sideways. 

That's waaay too much work.

**Comment by Allanitomwesh** [comment] 2015-03-30 08:29
A suggestion,you can name the current clear queue to "clear remaining queue" as that better describes the action. Then as @aminb suggested you can have "empty queue" inside show queue.

**Comment by notfoss** [comment] 2015-04-03 10:14
> I'm proposing we rename the current Clear queue to Dequeue next songs, and add an Empty queue that does what everyone is asking (clear out the whole queue).

This seems to be the best option. I doubt many people are happy with the current behaviour.

**Comment by aminb** [comment] 2015-04-04 04:42
@Allanitomwesh @notfoss yeah that's the best way I could think of.

So, @adrian-bl are you OK with the following?

Rename the current `Clear queue` to `Dequeue rest`;
and add `Empty queue` (**here**: [ShowQueueActivity.java#L75](https://github.com/vanilla-music/vanilla/blob/f058f21b97fb638162df1b93195f1ee7e1138bc1/src/ch/blinkenlights/android/vanilla/ShowQueueActivity.java#L75)) that does what everyone is asking (clear out the whole queue).

**Comment by Allanitomwesh** [comment] 2015-04-04 05:03
You could also remove "clear queue" aka "dequeue rest" from playback screen since it is duplicated inside show queue. Personally thing all the queue editing options should be in show queue,it's neater that way,and you can see what you are changing.

**Comment by adrian-bl** [comment] 2015-04-04 08:28
@aminb this is fine with me.
But i still do not see why someone really wants to drop the whole queue: Going to the library screen, selecting a new song and then hitting play does exactly the same (flushes queue and inserts the new selection at position 1). But meh :-)

**Comment by Allanitomwesh** [comment] 2015-04-04 14:17
Finally figured out what you meant by selecting play in library, but that is more of a replace queue action (as in it removes the old tracks and puts the new ones but the queue still isn't empty) 
Sometimes you just wanna start from zero, pick track by track,and enqueue them not play,build a playlist first,then play :)

**Comment by aminb** [comment] 2015-04-04 17:21
@adrian-bl I do see your point about using 'Play' to empty the queue and start from scratch, but considering this "issue" has been brought up several times by different users, it'd be nice to have this option.

**Comment by adrian-bl** [comment] 2015-04-05 13:07
@aminb yeah - don't get me wrong: i'm not against implementing this feature - it is just a way to use vanilla music i could never imagine ;-)

**Comment by aminb** [comment] 2015-04-05 15:27
@adrian-bl Yeah it's all good! Thanks for clarification though :beers:

**Comment by notfoss** [comment] 2015-04-06 04:43
@adrian-bl 

https://xkcd.com/1172/

Different users have different expectations and different ways to use software ;)

**Comment by aminb** [comment] 2015-04-14 01:05
@adrian-bl Can you please take a look at #160 ?

**Comment by aminb** [comment] 2015-04-15 21:37
**Empty queue** has been added in 7b6fc62. The only thing left to do is to rename "Clear queue" to "Dequeue rest" or a better alternative.

Suggestions anyone? If not, we'll go with "Dequeue rest" as discussed before.

**Comment by notfoss** [comment] 2015-04-16 08:31
"Dequeue rest" is the most intuitive term for the current behaviour. +1

**Comment by Allanitomwesh** [comment] 2015-04-16 11:06
+1 as well or "Dequeue Remaining" as an alternative wording.

**Comment by ToNIX-** [comment] 2015-04-16 13:14
What about "Trim remaining queue"?

**Comment by aminb** [comment] 2015-04-16 13:15
@notfoss +1
@Allanitomwesh +1

@ToNIX- Unfortunately that's too long for a menu option, but thanks.

**Comment by adrian-bl** [comment] 2015-04-22 19:08
Fixed in master, see: https://github.com/vanilla-music/vanilla/commit/71df5071e805c693189647f9e6cb2a08928ba2dd - transifex should pick up the change in a few days/hours, so the translations of the new string should be ready in a few days.

**Closed by adrian-bl** 2015-04-22 19:08 UTC
Labels: enhancement

**Comment by mase76** [comment] 2015-06-07 21:29
I don't get the usecase of dequeue remaining. When you say, empty queue doesn't make a sense, dequeue remaining makes less sense.

**Comment by aminb** [comment] 2015-06-07 21:45
@mase76 Dequeue rest (previously Clear queue) was the only option vanilla had for a long time, and that was how other devs wrote it. However, due to popular demand, we recently added Empty queue.

Basically, the argument here is that Dequeue rest clears the upcoming songs in your queue (in case you've changed your mind about what you're gonna listen), and if you want to completely start from scratch, you just do a Play action on one of the songs from library and that will empty the whole queue and add the new song. So, really, no *need* for empty queue.

If this doesn't make sense, @adrian-bl might be able to explain better.

**Comment by Allanitomwesh** [comment] 2015-06-08 10:59
@mase76 Empty queue performs the clear queue function you are looking for (clears everything) Dequeue rest does just that (clears songs NOT YET PLAYED but in queue) and is not a complete clear.
