### ISSUE TITLE
file\listdeletion

### ISSUE THREAD

**Issue by M1Aston** [vanilla-music/vanilla#938] opened 2019-03-21 17:33 UTC
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About):1.0.82
- Android Version:8
- Phone vendor / model: Xperia X
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ x] No
  - [ ] NA / Don't know.

## Description
File detection and file deletion don't work properly.
Flies deleted by Vanilla still show up in Windows (10) other players (I have checked a few) and in, but they can't be played. So the file is gone  but the the "file information" is still present.
(And yes, because of Vanille not having a sleep timer, I need a second player just for that)

The files tab and the tracks tab don't always correspond. Files tab usually shows the correct (amount of)  files, while the tracks tab often shows files that were deleted. An error message is shown when trying to play them.

**Comment by adrian-bl** [comment] 2019-03-29 19:22
This is a duplicate of #771

**Closed by adrian-bl** 2019-03-29 19:22 UTC
