### ISSUE TITLE
After 1.0.47 update the program sees not all tracks

### ISSUE THREAD

**Issue by teod0r** [vanilla-music/vanilla#511] opened 2017-01-18 10:26 UTC
It sees only 110 music tracks of 134 in /storage/sdcard1/Music. It was normal before update

**Comment by TheLastProject** [comment] 2017-01-18 11:18
I seem to be having a similar issue. In my case it seems to skip the .m4a files downloaded from YouTube with NewPipe in /storage/emulated/0/Music/NewPipe. When I instead open these files through the "Files" tab they play fine, but even the little bit of tagging NewPipe does is no longer visible.

I already told the media scanner in Vanilla Music to scan the whole filesystem, but even that is not enough to get it to show up.

CyanogenMod 14.1 (Android 7.1.1) on the Motorola Moto E 2015 LTE (surnia) here.

**Comment by adrian-bl** [comment] 2017-01-18 18:15
Could you send such an unindexed file to adrian@blinkenlights.ch?

**Comment by teod0r** [comment] 2017-01-18 20:45
Give me an easy way to get list of tracks in queue and I'll do

**Comment by adrian-bl** [comment] 2017-01-19 17:09
If you have root, you could do a 'select path from _songs' using sqlite3 - but i suppose that this issue is related to #517

**Comment by Allanitomwesh** [comment] 2017-01-28 12:38
I can confirm this issue with my .ogg music. It plays if I start it from file manager but not listed at all by vanilla in tracks or albums

**Comment by adrian-bl** [comment] 2017-01-28 13:30
Allan: thanks for the sample file.

The file was not indexed because it does not have any tags.

I removed this restriction, so the next release (should go live on sunday) will index such files

**Comment by adrian-bl** [comment] 2017-01-29 15:05
Closing this as a duplicate of #517 - 1.0.48 should soon show up on f-droid

**Closed by adrian-bl** 2017-01-29 15:05 UTC
