### ISSUE TITLE
Feature Request: Automatically read playlists from /storage/emulated/0/Playlists

### ISSUE THREAD

**Issue by doronbehar** [vanilla-music/vanilla#783] opened 2018-05-24 12:21 UTC
I have a script that syncs my playlists from the music player on my PC to my device and to a `Playlists` directory on the main storage (using [Syncthing](https://syncthing.net/)). I would be extremely pleased if Vanilla Music would read those and allow me to play these. I currently use VLC for that.

Plus, I think Vanilla Music should save his playlists there too.

With VLC, I've found out that it'd play the playlists only if the path to the music files was absolute, that's why I needed a script that will insert Android's absolute prefix path to the playlists' relative path (the music player on my PC works with relative paths). If Vanilla Music would read paths in the playlist file relative to the music directory, that would be awesome.

**Comment by adrian-bl** [comment] 2018-05-24 17:51
I agree, we totally should do this - looks like a dupe of #643?

**Comment by adrian-bl** [comment] 2019-02-03 08:33
This should be resolved by pull request #908: vanilla now reads (and optionally writes) relative playlists.

**Closed by adrian-bl** 2019-02-03 08:33 UTC
