### ISSUE TITLE
crash when scrolling in the queue

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#113] opened 2014-11-02 19:10 UTC
When holding down on the queue's scrollbar, I get a crash. Using 0.9.40 from fdroid.

**Comment by adrian-bl** [comment] 2015-01-05 17:45
This works for me: i do not get a crash (compiled -head on 5.0).

What version of Android are you running? Could you get us a logcat of the crash?

**Comment by mathstuf** [comment] 2015-01-05 18:18
It's on ICS 4.2.2 with a Galaxy Nexus. Poking it a bit more, it doesn't happen if paused, but it does if it is playing music at the time.

Logcat:

```
W/dalvikvm(25449): threadid=1: thread exiting with uncaught exception (group=0x40bb0930)
E/AndroidRuntime(25449): FATAL EXCEPTION: main
E/AndroidRuntime(25449): java.lang.NullPointerException
E/AndroidRuntime(25449):        at com.mobeta.android.dslv.DragSortController.onScroll(DragSortController.java:381)
E/AndroidRuntime(25449):        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:572)
E/AndroidRuntime(25449):        at com.mobeta.android.dslv.DragSortController.onTouch(DragSortController.java:243)
E/AndroidRuntime(25449):        at android.view.View.dispatchTouchEvent(View.java:7241)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
E/AndroidRuntime(25449):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(25449):        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
E/AndroidRuntime(25449):        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
E/AndroidRuntime(25449):        at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
E/AndroidRuntime(25449):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
E/AndroidRuntime(25449):        at android.view.View.dispatchPointerEvent(View.java:7426)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
E/AndroidRuntime(25449):        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
E/AndroidRuntime(25449):        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
E/AndroidRuntime(25449):        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4342)
E/AndroidRuntime(25449):        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4382)
E/AndroidRuntime(25449):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime(25449):        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime(25449):        at android.view.Choreographer.doFrame(Choreographer.java:530)
E/AndroidRuntime(25449):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AndroidRuntime(25449):        at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(25449):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(25449):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(25449):        at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(25449):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25449):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(25449):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(25449):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(25449):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  374):   Force finishing activity ch.blinkenlights.android.vanilla/.ShowQueueActivity
W/ActivityManager(  374): Activity pause timeout for ActivityRecord{41a91df0 u0 ch.blinkenlights.android.vanilla/.ShowQueueActivity}
```

**Comment by K-RAD** [comment] 2015-01-22 08:37
I have the same issue on android 4.2.2. If i try to drag the scrollbar in queue, the queue activity crashes. It's because of the newly added DragSortListView, it didn't happen on older versions

**Comment by aminb** [comment] 2015-01-22 20:58
@K-RAD I'll try the suggestion of the last comment on that issue (moving [this](https://github.com/vanilla-music/vanilla/blob/5d89a5604f11ae269c7b94520e1d1075605d1b41/src/com/mobeta/android/dslv/DragSortController.java#L243) line before the first if statement) and will upload a debug apk so you can test.

**Comment by adrian-bl** [comment] 2015-02-01 17:00
@aminb did you have time to work on this?

**Comment by aminb** [comment] 2015-02-01 18:13
@adrian-bl Oh, I did try the suggestion of that comment, but totally forgot to upload an apk! Will do when I get home.

**Comment by aminb** [comment] 2015-02-03 13:43
@adrian-bl @mathstuf @K-RAD Can you guys test this build and see if the issue is gone or not?

Download from here: http://www.fileconvoy.com/dfl.php?id=g370cae5fced3a2ca999618227a8e7e122a98693a3

If you know any better file upload services (without needing to register) tell me I'll upload it there.

**Comment by mathstuf** [comment] 2015-02-03 14:20
On Tue, Feb 03, 2015 at 05:43:42 -0800, Amin Bandali wrote:
> @adrian-bl @mathstuf @K-RAD Can you guys test this build and see if
> the issue is gone or not?

Glad to. However...

> Download from here:
> http://www.fileconvoy.com/dfl.php?id=g370cae5fced3a2ca999618227a8e7e122a98693a3

Do you have a sha1sum or something we can expect?

Thanks.

**Comment by mathstuf** [comment] 2015-02-03 14:26
On Tue, Feb 03, 2015 at 05:43:42 -0800, Amin Bandali wrote:
> If you know any better file upload services (without needing to
> register) tell me I'll upload it there.

<hack level="nasty">

```sh
base64 < *.apk | gist
```

</hack>

If you're desperate. *shudder* Still better than many upload services
though.

**Comment by K-RAD** [comment] 2015-02-03 15:31
seems to be solved on my device

**Comment by aminb** [comment] 2015-02-06 12:32
@mathstuf Did you get a chance to test the APK? Does it solve the issue for you too?

**Comment by aminb** [comment] 2015-02-15 16:20
Since I didn't hear from @mathstuf and the issue seems to be solved for @K-RAD I'll be pushing the fix today and will close this issue.

**Closed** 2015-02-21 14:01 UTC
Labels: bug
