### ISSUE TITLE
Forward and backward rewinds

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#810] opened 2018-08-18 14:20 UTC
This was posted in "0 tracks playing" issue: "also add controls to fast forward and rewind for audio books".

I have one music album per mp3 file, and I need "Skip T sec/min Forward /  Backward" feature; the T configurable in settings. The time-slider just don't work with the long audio files.

Suggestion: Add extra control buttons to the track screen. Maybe second row above what we have now.

The dev has already stated to me that he don't want support long mp3 files, including audio books. I don't understand why not; nothing too complicated will be added here. Just basic functionality what every audio player should have, whether music player or not.

**Comment by andiandi13** [comment] 2018-08-18 17:17
Do you know that you can add gestures to do that ?

Go to 'Playback Screen' in settings.

Personnaly, I use swipe up for '10sec forward' and swipe down for '10sec backward'.

**Comment by adrian-bl** [comment] 2018-08-19 10:43
Duplicate of your (!) bug #779 where you claimed to not have "patience to read manuals" which i find incredibly insulting.

-> As andiandi13 mentioned (and i did back then): there is the swipe up feature
-> If we would add a button for every single thing, the whole user interface of vanilla music would be a collection of hundreds of buttons.

**Closed by adrian-bl** 2018-08-19 10:43 UTC
