### ISSUE TITLE
Artist name correction impossible

### ISSUE THREAD

**Issue by cubetronic** [vanilla-music/vanilla#153] opened 2015-04-06 16:45 UTC
you can't correct an artist name from lowercase to uppercase, like "django django" to "Django Django".

i cleared the cache, uninstalled, rebooted, deleted the media, etc. whenever i put the media back on my SD card, Vanilla would show the old name. it's not reading what i put on there, it's reading something else, some cache somewhere, i'm guessing on the phone storage (not SD storage).

it seems pretty weird that it remembers this even after an uninstallation and reboot. bad news.

... also... i tried to change "The Ramones" to just "Ramones", as it should be, and it couldn't do that either.

**Comment by adrian-bl** [comment] 2015-04-07 06:18
Vanilla Music uses Androids media database.
A reboot of the phone should normally trigger a re-scan but this seems to fail on your phone for some reason.

You can manually trigger a reboot by using this app: https://play.google.com/store/apps/details?id=com.gmail.jerickson314.sdscanner

It will force a re scan of androids media database.

**Comment by cubetronic** [comment] 2015-04-07 16:37
I installed that SD Scanner. It says it's compatible with Android 4.4 and 5.0, but I'm using 4.3.1. I tried it anyway, with no luck. Rebooted, tried again, no luck. I can see that the SD Scanner is pausing on some of the file names in question when it does its scan, but it's not effective.

Vanilla Version: 0.9.42
Phone Model: LG-P930
Android Version: 4.3.1
CyanogenMod Version: 10.2.1-p930

This is the latest stable version of CyanogenMod for my phone. The latest stock version is Android 4.0. Earlier this year I tried a nightly build of CyanogenMod: Version 11, with Android 4.4.x, but from what I remember it seemed buggy and I preferred the latest stable.

Why not add a refresh option?

**Comment by adrian-bl** [comment] 2015-04-07 17:31
Vanilla Music *had* a refresh function but it broke with every release as google likes to change this API all to often.

That said: It shouldn't even be required to have this option in an audio application - i'm sorry but this is clearly a bug in your ROM.
In the worst case you can try to remove the 'wrong' songs and re-add them: this should trigger a rescan in any case.

**Comment by cubetronic** [comment] 2015-04-08 16:10
I already tried removing the wrong songs and re-adding them. And I tried that several times, several different ways, doing reboots and clearing cache, etc.

VLC and SicMu Player don't have this problem. It's just Vanilla and Just Player.

I also tried going into ClockworkMod and clearing the cache. It took a while for the system to start up again as a long list of apps went through an initialization process. This also did not solve the problem. I also deleted the Dalvik-Cache, for good measure.

**Comment by aminb** [comment] 2015-04-11 13:35
@cubetronic Do you have this issue with other ROMs?

**Comment by cubetronic** [comment] 2015-04-11 23:19
i don't use other ROMs.

*i'm* the one who brought up "buggy ROM" - shouldn't have said that. i was talking about a *different* ROM that was buggy, that i do NOT want to use.

and there's probably other people using the exact same ROM as me. either with the exact same phone, or with CyanogenMod 10.2.1 on another phone.

can i just run a command or something? it would be nice to fix this without flashing my whole phone. can you at least tell me some directories i can hack at or delete? i tried deleting a ch.blinkenlights.... directory somewhere when i had some extra time.. no luck.

**Comment by aminb** [comment] 2015-04-12 00:16
This is strange. I know whenever I add new songs, I always have to reboot the phone to trigger a re-scan, but that always does it; and it's very strange that after doing all the things you mentioned, the database doesn't get updated.

As Adrian mentioned, since Vanilla uses Android's media database, AFAIK there's not much fiddling you could do in terms of deleting files/directories. @adrian-bl Do you know any?

I've re-opened the issue for now, and I'll try to look for bugs for that specific CM version, but I doubt I'd be able to find anything useful.

I'll also try to take a look at VLC and SicMu, but really if the issue is related to Android media DB (which is what I'm guessing since you say Just Player also has issues), I don't think that would be of help much either.

**Comment by cubetronic** [comment] 2015-04-12 05:46
Correction: SicMu Player also has the same issue.

VLC is the only player I know of that does NOT have this issue.

*Just Player* is funny in that it has the issue, but it also has an edit feature... When I open the song to edit it, it shows up just fine, with the proper case.

**Comment by cubetronic** [comment] 2015-04-12 06:53
i found a fix:
Settings -> Manage apps -> Media Storage -> Force stop *and* Clear data -> Reboot

**Comment by aminb** [comment] 2015-04-21 12:41
@cubetronic Is your fix still working? If yes, we can close this issue, since I don't really think this is an issue with Vanilla.

**Comment by cubetronic** [comment] 2015-04-21 21:44
ya it's fine. OK to close. thanks.

**Comment by aminb** [comment] 2015-04-21 23:38
@cubetronic good to hear; np :)

**Closed by aminb** 2015-04-21 23:38 UTC
