### ISSUE TITLE
crash oneplus cm11 4.4.4 xposed several occasions memory leak and illegal expectation

### ISSUE THREAD

**Issue by y7575355** [vanilla-music/vanilla#298] opened 2016-03-07 05:34 UTC
Cracker catches the debug
1. Out of memory

java.lang.OutOfMemoryError
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:708)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:595)
    at ch.blinkenlights.android.vanilla.CoverBitmap.createScaledBitmap(CoverBitmap.java:334)
    at ch.blinkenlights.android.vanilla.CoverBitmap.createBitmap(CoverBitmap.java:137)
    at ch.blinkenlights.android.vanilla.CoverView.generateBitmap(CoverView.java:375)
    at ch.blinkenlights.android.vanilla.CoverView.handleMessage(CoverView.java:462)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)
1. Illegal expectation

java.lang.IllegalStateException
    at android.media.MediaPlayer.prepare(Native Method)
    at ch.blinkenlights.android.vanilla.PlaybackService.prepareMediaPlayer(PlaybackService.java:639)
    at ch.blinkenlights.android.vanilla.PlaybackService.triggerGaplessUpdate(PlaybackService.java:760)
    at ch.blinkenlights.android.vanilla.PlaybackService.handleMessage(PlaybackService.java:1553)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)

Thank you for a wonderful app

**Comment by adrian-bl** [comment] 2016-03-10 07:19
Looks like a dupe of #268

**Comment by xbao** [comment] 2016-03-11 06:48
@adrian-bl I think the second stack is a duplicate of #268, but the first seems to be different. Both are mentioned in #248. 

The device has 3GB of RAM, it's likely we're hitting the 32mb heap limit. Which is bizarre, even if the album art was huge we're only creating a Bitmap as large as is needed.

@y7575355 What screen are you on when this happens?

**Comment by adrian-bl** [comment] 2016-03-11 07:56
@xbao i agree that the first one is different, sorry: i overlooked this (i'm currently sick, so i blame the fever ;-) )

**Comment by y7575355** [comment] 2016-03-11 12:16
My home screen usually
Nemus
Or playback screen in vanilla

**Comment by xbao** [comment] 2016-03-12 00:32
@adrian-bl Bleugh, no worries :)

@y7575355 Home screen with the Vanilla widget visible?

**Closed** 2017-02-05 09:02 UTC
Labels: bug
