### ISSUE TITLE
Add section to README on ID3 tag support

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#596] opened 2017-05-15 10:27 UTC
Please add a section to README.md on ID3 tag support. What is supported and what is not (2.3.0 vs. 2.4.0) and what encoding is recommended (UTF8/UTF16). What are common problems (numbers in genres, conversion problems with Â or Ãᵃ in names) and how to solve these.

**Comment by adrian-bl** [comment] 2017-05-28 16:32
The problem is that this depends on the device: ID3v2.4 is supported by android itself and the encoding issues vary between device versions.

**Comment by adrian-bl** [comment] 2017-12-03 14:01
Closing this as wontfix: The exact media support depends on the device firmware.

**Closed by adrian-bl** 2017-12-03 14:01 UTC
