### ISSUE TITLE
[Bug] Long press repeat icon does nothing

### ISSUE THREAD

**Issue by collectorgeneral** [vanilla-music/vanilla#597] opened 2017-05-17 22:28 UTC
Details:

Lineage OS 14.1 (Android 7.1.2) on Oneplus One
Vanilla Music version: 1.0.52
Source: F Droid

Problem description:

- To reproduce, just open Vanilla music and on the playback screen, long tap the 'repeat' option (the one next to the controls).

What happens?

- Nothing. I feel a haptic feedback but then, nothing. 

What should have happened? 

- A "pop up" menu showing various repeat options.

**Comment by adrian-bl** [comment] 2017-05-25 19:09
This is a known Android 7.x only issue: The menu is misplaced, but only in the full playback view.

The same code works in the library view and on any Android Version < 7.

I was hoping that google fixes this regression, but its still present in 7.1.2, so we should probably try to find a workaround.

**Comment by adrian-bl** [comment] 2017-06-09 21:17
Fixed via efb107b063ffae88674ace5cdb4ef06eeb001cf2

Turns out that android didn't like that we passed a modified MotionEvent to the button view.

This worked in the LibraryActivity as the buttons there got the original event (because we didn't intercept their onTouch()'s)

**Closed by adrian-bl** 2017-06-09 21:17 UTC
