### ISSUE TITLE
Cannot show queue when controls are hidden

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#459] opened 2016-10-29 21:25 UTC
When the controls are hidden on the `Now Playing` view, hitting `Show queue` does nothing visibly. Bringing the controls back immediately shows the queue.

1.0.45 from F-Droid on Nexus 5X with Android 7.0.

**Comment by aminb** [comment] 2016-10-29 22:24
Thanks for report, I can reproduce this too.

**Comment by adrian-bl** [comment] 2016-10-30 08:58
Thats because we are setting the visibility of parent view shared by the queue and the controls.

Just curious: does someone really use the hide controls feature? I was thinking about removing it as it often seems to confuse users (got many emails and some playstore users complaining about it in the past few years).

**Comment by ard-108** [comment] 2016-11-09 21:19
Nice Player. I find this feature very useful on a small screen. As i can do most function i want  by long press, short press or flick. I only really use the bar when i want to change to random play or pull up the queue list. I really appreciate that the screen is not cluttered.

**Comment by adrian-bl** [comment] 2017-04-15 18:47
Fixed in the latest nightly

**Closed by adrian-bl** 2017-04-15 18:47 UTC
Labels: bug
