### ISSUE TITLE
Support performing the "play/enqueue all" action  on individual tracks in folder view

### ISSUE THREAD

**Issue by The0x539** [vanilla-music/vanilla#486] opened 2016-12-11 19:29 UTC
Standard track view does this, enqueueing all tracks from after the selected track, then all those from before, but folder view, even if "play all" is selected as the default action, simply replaces the queue with the chosen track.

**Comment by adrian-bl** [comment] 2016-12-13 18:04
This looks like a duplicate of #352

**Closed** 2016-12-18 08:57 UTC
