### ISSUE TITLE
Headphone Controls: Vanilla dies when pausing 

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#223] opened 2015-10-08 22:06 UTC
To reproduce:

1. Plug in headphones with a media control button
2. Start playing something
3. Send Vanilla to background
4. Clear from recent apps (presumably this also happens if the app is cleaned up in the background by the OS)
5. Press the headphone media button to pause the music
6. Press the headphone media button 
 Expect: Music resumes
 Actual: Nothing

Logs show:

```
9:03:25.973 Got event KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_HEADSETHOOK, scanCode=226, metaState=0, flags=0x8, repeatCount=0, eventTime=24389144, downTime=24389144, deviceId=2, source=0x101 }
9:03:25.980 Got event KeyEvent { action=ACTION_UP, keyCode=KEYCODE_HEADSETHOOK, scanCode=226, metaState=0, flags=0x8, repeatCount=0, eventTime=24389144, downTime=24389144, deviceId=2, source=0x101 }
```

Then the service dies.

Probably causing some subset of the issues #207 and #96

**Comment by xbao** [comment] 2015-10-08 22:28
I can consistently reproduce it on a  5.0.2 stock ROM xperia z3+ but not at all on a 5.1.1 custom ROM moto g2. Very strange.

Possibly caused by use of the deprecated [RemoteControlClient](https://developer.android.com/reference/android/media/RemoteControlClient.html). Deprecated in lollipop: [Android 5.0 Behavior Changes](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorMediaControl). Changing that might be an issue as there doesn't seem to be a consistent way to support lower API's: [Do MediaSession and MediaSessionManager have backward compatibility?](https://stackoverflow.com/questions/27738407/do-mediasession-and-mediasessionmanager-have-backward-compatibility?lq=1)

**Comment by adrian-bl** [comment] 2015-10-09 10:39
I lost my only pair of headphones with a remote controll yesterday, so i can not do any tests right now ;-)

But PlaybackService calls unregisterMediaButton on shutdown - maybe we should just skip this call?

**Comment by adrian-bl** [comment] 2015-10-09 18:43
Ok, got a new pair and played with this on my Moto G (gen 1, stock) and it also seems to work ok there: i can kill the service and clicking the button will launch vanilla music (unless some other app registered itself in the meantime).

The only think i can think of is that removing the app from the recents view wll call PlaybackService:onDestroy() which does unregister itself.

I do not think that unregistering makes any sense as any app that registers itself after Vanilla Music will win anyway. (and calls to onDestroy() are random)

About MediaSession: I played with the new API a few days ago but couldn't get the metadata working (my BT device never showed any metadata while displaying artwork on the lockscreen worked just fine) :-/

**Comment by snelltheta** [comment] 2015-10-14 19:32
Just got headphones with control off of the ground while walking. The pause and volume buttons work perfectly on LG G3 with lollipop only when screen is off. When screen is on only volume buttons work, not the pause button.

**Comment by adrian-bl** [comment] 2015-11-08 12:42
I removed the unregister code for now (d2d3171095a110da5009372e179bba5f6c139ab8) and going to close the issue.
I'm pretty sure that this issue is caused by the unregister call onDestroy() and even if not: there isn't much we could do about it :-)

**Closed by adrian-bl** 2015-11-08 12:42 UTC
