### ISSUE TITLE
Some albums appear in the wrong order

### ISSUE THREAD

**Issue by n-o-o-b** [vanilla-music/vanilla#797] opened 2018-07-28 20:47 UTC
- Vanilla Music Version (Settings -> About):
- Android Version: 7.1.2 (LineageOS 14.1)
- Phone vendor / model: Motorola Moto E 2nd Gen 4G
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
Some of my albums display with the tracks in the wrong order. This has happened for both MP3 and FLAC albums.

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

Wrong order:

![screenshot_20180728-213950 1](https://user-images.githubusercontent.com/19697175/43360550-11e5217a-92af-11e8-805f-458f4ff67e90.png)

Correct order:

![screenshot_20180728-214006 1](https://user-images.githubusercontent.com/19697175/43360579-a28c61ac-92af-11e8-846d-f0e50ebcedd2.png)

![screenshot_20180728-214313 1](https://user-images.githubusercontent.com/19697175/43360563-52e3b0f6-92af-11e8-968d-a5ff27d76510.png)

![screenshot_20180728-214334 1](https://user-images.githubusercontent.com/19697175/43360567-60a0e664-92af-11e8-87eb-00c758ad9abc.png)

etc.

(And for some reason in that second example, Vanilla doesn't display the embedded artwork as well.)

**Comment by adrian-bl** [comment] 2018-07-29 04:44
Which sort option is selected?

**Comment by n-o-o-b** [comment] 2018-07-29 06:55
Default, I think. It says "artist, album, track number".

**Comment by andiandi13** [comment] 2018-07-29 08:49
I had the same "issue" with one album, until I realized the track numbers were not correct.

Indeed, it was an album with **3 discs** but in the ID3 tags, every track was Disc 1, so there was three track 1, three track 2 etc.. until the end.

So the order was :

- Track 1 - Disc 1
- Track 1 - Disc 2 (named 1 on the tag)
- Track 1 - Disc 3 (same)

So check your tags, maybe the issue is there.

**Comment by n-o-o-b** [comment] 2018-07-29 09:45
This was an album with 1 disc, so it can't be that. I had ripped it myself from the CD with CUERipper, so I don't think there are any issues with the tags. I have an issue with how multi-disc albums are displayed but that's another discussion and I think I should open another thread for that.

**Comment by adrian-bl** [comment] 2018-07-29 09:55
Long click on the title in the playback view.

This will show you additional information, such as the track number tag.

I'm 100% sure that the issue is with your tags as sorting works for everyone else.

Maybe you have a mix between ID3v1 and v2

**Comment by n-o-o-b** [comment] 2018-07-29 10:02
The tags are FLAC. It's not ID3. For the Wiley album, that is.

![image](https://user-images.githubusercontent.com/19697175/43365065-9ff09408-931e-11e8-839b-a884f53fe265.png)

For the jungle album, you may be right.

![image](https://user-images.githubusercontent.com/19697175/43365058-9113bf32-931e-11e8-8013-9a45c3c07402.png)

While we're on the subject, is there any way you could make the app display track numbers in the track view? Would be very useful, and would make it instantly clear if the tracks are displaying in the wrong order.

**Comment by adrian-bl** [comment] 2018-07-29 10:09
Please post a picture from vanilla musics playback view, as requested above.

A screenshot of a tag editor doesnt help.

**Comment by adrian-bl** [comment] 2018-07-29 10:12
Also note that both albums have multiple artists and that you are sorting by

Artist, album, track

**Comment by n-o-o-b** [comment] 2018-07-29 10:13
![screenshot_20180729-111154 1](https://user-images.githubusercontent.com/19697175/43365163-5cd619e8-9320-11e8-9b75-d2ffd9e7d9da.png)

![screenshot_20180729-111219 1](https://user-images.githubusercontent.com/19697175/43365167-67557d3c-9320-11e8-966c-5b54e0440129.png)

**Comment by n-o-o-b** [comment] 2018-07-29 10:14
Wait, so you're saying it's supposed to sort like that with that sort option? If so, you should change the default option to sort by track numbers first so that stuff appears in the right order.

**Comment by adrian-bl** [comment] 2018-07-29 10:19
You can always change the sort option to "album, track".

The default sorting may not be great for albums with multiple artists but is better if you filter by genre.

**Comment by n-o-o-b** [comment] 2018-07-29 10:30
Changing that sort option seems to have fixed it. So was there actually a problem with the tags on the MP3 (since MP3 tag said "ID3v1 ID3v2.3") or was it just the sort option?

**Comment by adrian-bl** [comment] 2018-07-29 10:51
Just the sort optition

**Comment by n-o-o-b** [comment] 2018-07-29 11:07
BTW, I have another issue where some albums by Various Artists appear in the list with the name of one of the artists from the album underneath. Do you know what might be causing this?

![screenshot_20180729-112935](https://user-images.githubusercontent.com/19697175/43365657-f209c83c-9327-11e8-8f76-9f97747472d9.png)

**Comment by adrian-bl** [comment] 2018-07-30 07:40
Thats expected: we pick a random (usually the first seen) artist of an album to be displayed in the album listview.

**Comment by andiandi13** [comment] 2018-07-30 09:22
@n-o-o-b First question : Because the name of the album is too long and prevail over the artist.

**Comment by adrian-bl** [comment] 2018-07-30 16:34
As andiandi13 already mentioned, the artist is now shown because the long title 'pushed it out' of the view.

Regarding AlbumArtist: You are correct that this would be the better tag to display.
We use 'Album' mostly for historic reasons: AlbumArtist is relatively new and also an optional tag.
We should probably change this in a future release (which requires a small DB update as we would need to make albumartist non-optional and therefore pre-fill the database)

**Comment by adrian-bl** [comment] 2018-08-02 06:12
I opened bug #801 about the album-artist issue.

Going to close this issue as the sorting works as expected.

**Closed by adrian-bl** 2018-08-02 06:12 UTC

**Comment by eggsgent** [comment] 2018-09-28 16:55
Hi, will #801 fix the mixing of two albums with same name (eg. "Greatest Hits") by different artists?

I'm using mp3tag program, id3v.2.3 only, Artist and Album tags (Album artist tag only for VA). This leads to Vanilla Music mashing these two albums together.
