### ISSUE TITLE
[Request] Playlist songs in "SONGS"

### ISSUE THREAD

**Issue by InstallGentoo11** [vanilla-music/vanilla#440] opened 2016-09-20 12:47 UTC
I really like the SONGS tab the most. Going to playlists for example and opening a playlist is just not the same. You don't even have the sort options there, nothing really. I would like if you could add an option where the current playlist you are playing is the only thing displayed in SONGS or just modify the PLAYLIST tab so it would look like SONGS and have the same functionality as SONGS once you choose a playlist.

**Comment by adrian-bl** [comment] 2016-10-05 11:40
yeah: the playlist dialog is some kind of special snowflake.
I'm closing this bug as a duplicate of #372 as this is in the end the same issue/feature

**Closed by adrian-bl** 2016-10-05 11:40 UTC
