### ISSUE TITLE
Display new songs in vanilla

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#373] opened 2016-06-04 17:23 UTC
When we copy new music files, we have to wait a certain time for them to display in vanilla.

What I do against that, is killing "Media Storage" app, which also kills vanilla and display all the newer Songs when we open it again.

So I Think a new option should be added in vanilla to reload the library, you can for example add an option that kills media storage and restart vanilla automatically.

**Comment by adrian-bl** [comment] 2016-06-05 07:42
Duplicate of #312

**Closed by adrian-bl** 2016-06-05 07:42 UTC
