### ISSUE TITLE
[BUG] Misbehaves after hardware NEXT/PREVIOS buttons

### ISSUE THREAD

**Issue by teod0r** [vanilla-music/vanilla#334] opened 2016-05-03 09:14 UTC
I have Samsung Galaxy Tab4 10.1 and volume buttons set to play next/previos songs when holded when screen is turned off. After selecting a next song with the hardware button, when I turn on the screen the widget and the application misbehave: when I push "next" it plays the first song instead of next, when I push "pause" it plays the first song instead of pause.

**Comment by adrian-bl** [comment] 2016-05-04 08:56
With widget, do you mean the notification on the lockscreen or a real widget?
Could you get us a logcat while this happens?

But in any case i doubt that there is much we can do, as this really smells like a firmware bug of your tablet.

**Comment by teod0r** [comment] 2016-05-08 12:12
I mean a real widget.

I discovered that if I clear data of Vanilla Music in the android settings, the problem is gone for some time.

I will attach a logcat later when the problem appears again.

**Comment by adrian-bl** [comment] 2016-07-17 15:55
closing this issue as i'm not able to reproduce it

**Closed by adrian-bl** 2016-07-17 15:55 UTC
