### ISSUE TITLE
[Bug] Player plays random tracks when switching modes.

### ISSUE THREAD

**Issue by collectorgeneral** [vanilla-music/vanilla#283] opened 2016-02-08 22:39 UTC
I have noticed this strange behaviour recently, and until today I was not sure how to reproduce it. Here is what to do to reproduce the issue:

->Select some track from some album.
->Change 'mode' to repeat single track.
->Decide dont want, change back to no repeat mode by touching several times to get back to the option.

Now once the track ends, suddenly another unrelated track starts playing. 
Does not seem to appear if you do not change the repeat options.

**Comment by adrian-bl** [comment] 2016-02-09 16:46
Hmm.. This works for me.

Are you always cycling through the options or do you switch by long-press?

Does the shuffle mode impact the outcome?

**Comment by collectorgeneral** [comment] 2016-02-09 22:31
I always cycle through options. Long press method does not appear to reproduce it. However, now that you mentioned it, I tried going to one option after an other. So the "Random" option appears to be casuing the issue. I did the long press->Random. Then long press -> Back to no repeat. Causing the same behaviour.

**Comment by adrian-bl** [comment] 2016-02-10 07:18
Ah: now i get it: so you are cycling from repeat-current-song to no-repeat by cycling trough random mode with only one song in the queue, correct?

In this case, the outcome would be the expected behaviour as going 'random' automatically adds a new song to the queue.
This song will not be removed after leaving the random mode: the automatically selected song became a normal part of the queue.

**Comment by collectorgeneral** [comment] 2016-02-17 04:07
Sorry for the late repl. Using the same stepsto play an album does not cause the same behaviour. Are playing tracks vs albums managed differently?

**Comment by adrian-bl** [comment] 2016-02-20 11:34
Somewhat: Vanilla Music might restore the ordering of an album if you reach the 'shuffle albums' state

**Comment by collectorgeneral** [comment] 2016-02-21 15:40
What shuffle album state? I see 5 options, No repeat, Repeat, Repeat current song, stop after current and Random. Isnt shuffle a completely different option? 
Anyway, from what I see, it actually 'cancels' the random mode after you exit it. I tried experimenting with the option, so I played the album without changing the random mode, and as expected random songs were added towards the end of the album. Now if I cycle through it to come to no repeat mode again, no random songs were added and the album stoped where it was supposed to. 
If I did the same by playing a particular track in the same album, it does that behaviour I described earlier.
I personally think the way it handles the album case is better, if the random mode is still enabled when the track/album finishes, then continue playing the random songs. Otherwise do not. Something like this would be good right?
Whats your opinion on this?

**Comment by adrian-bl** [comment] 2016-02-21 19:26
> What shuffle album state?

The one on the left side.
Note: In 'Vanilla Slang': The 'dices' are 'Random mode' while the options on the left are 'shuffle'.

> Now if I cycle through it to come to no repeat mode again, no random songs were added and the album 
> stoped where it was supposed to. 
>  Whats your opinion on this? 

Random songs are only added if vanilla music (for some reason) is: in random mode and starts playing the last song in the queue.

We have way to many playback options and things might get confusing - could you create a video of the issue while you are hitting it? This will make it simpler to reproduce the issue on my device.
You can do this via:
     adb shell screenrecord /sdcard/vanilla.mp4

(See: http://developer.android.com/tools/help/shell.html#screenrecord)

**Comment by collectorgeneral** [comment] 2016-02-23 23:20
Oops, I should have been clearer. I do not actually touch the shuffle option. 

> Random songs are only added if vanilla music (for some reason) is: in random mode and starts playing the last song in the queue.

Ah yes, that is it! I can confirm that this is the case. This would explain why it behaves differently for album vs track case. I typically do not change that option towards the end of the album so no wonder I have not encountered it. But since you said that, I gave it a shot. I first cycled through the otions while playing a particular track in the album which is NOT the last track. And it does not add random tracks.
Now if I cycle through the options while playing the last track, the random track is added!
If you want a video, heres one I captured.
[Telecine_Vid.zip](https://github.com/vanilla-music/vanilla/files/143616/Telecine_Vid.zip)

As you can see, I play an entire album at the start. For the first 12 seconds, I change through tracks, and before the last track I cycle through the options. Nothing happens. Then I cycle the options at the last track and as you said, it adds the random track.
This explains the single track scenario too, since it is technically the 'last' track.
From what I understand, you seem to be not expecting it too. Let me know what you think.

**Comment by adrian-bl** [comment] 2016-02-27 15:25
> From what I understand, you seem to be not expecting it too. Let me know what you think.
Thanks for the video: What you are seeing is the expected behavior, but i can understand your confusion:

At 00:27 you are switching to Random (Dices) mode while 'You Can Do It' is active.
This is the last song in the queue and causes vanilla music to add a new random song at the end of the queue: Exiting the Dice-Mode will not remove such an auto-appended song. That's why '9th Heaven' will be the next song even after leaving the random mode.

**Comment by collectorgeneral** [comment] 2016-02-27 16:39
Yes, I understood that part! 
My question now would be, Is it possible to put this behaviour towards the END of the last track rather than the START of the last track? So like after the last track finishes playing, then append a random track if the random mode is enabled, otherwise just stop playing? I personally think that it would be nice if it were that way. If you think its not possible or feasible, then its fine too!

**Comment by adrian-bl** [comment] 2016-02-28 12:23
That's not possible as VanillaMusic needs to know the next song while *starting* to play the current one (for the cover swipe and replay gain)

The only thing we could do is to remove the auto-added song in this case, however: the queue currently does not know why the song was there and this would require quite some changes.

**Comment by collectorgeneral** [comment] 2016-03-01 01:21
Hm, I see, it makes sense. I guess it might not be the top of your priorities, but just put it somewhere on your list! Maybe you will get to sort it out some day!

**Comment by adrian-bl** [comment] 2016-04-08 20:33
Keeping this open as a reminder to myself:

On a rainy day, i shall implement something like a queue source flag where the last song added by 'random mode' might get nuked in certain cases (eg: enqueue)

**Comment by adrian-bl** [comment] 2016-10-30 14:51
This issue has been fixed in commit https://github.com/vanilla-music/vanilla/commit/bcd64a46d43b4e6cf59ce1e6224d1c80a4dff7f4

**Closed by adrian-bl** 2016-10-30 14:51 UTC
Labels: bug
